import * as path from 'node:path';
import { NormalizedSpec, NormalizedOperation } from '@postmcp/core';
import { GeneratedProject } from './types.js';

export { GeneratedProject };

function pythonIdentifier(name: string): string {
  // Convert camelCase or kebab-case to snake_case
  const s = name
    .replace(/([A-Z])/g, '_$1')
    .toLowerCase()
    .replace(/[^a-z0-9_]/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '');
  return s || 'tool_func';
}

function mapSchemaToPythonType(schema: any): string {
  if (!schema || !schema.type) return 'str';
  if (schema.type === 'integer') return 'int';
  if (schema.type === 'number') return 'float';
  if (schema.type === 'boolean') return 'bool';
  if (schema.type === 'array') return 'list';
  if (schema.type === 'object') return 'dict';
  return 'str';
}

export function generatePythonProject(spec: NormalizedSpec): GeneratedProject {
  const files: Record<string, string> = {};

  const serverName = spec.title.toLowerCase().replace(/[^a-z0-9]/g, '_') || 'mcp_server';
  const baseUrl = spec.servers.length > 0 ? spec.servers[0].url : 'https://api.example.com';

  // 1. requirements.txt
  files['requirements.txt'] = `mcp>=1.2.0
httpx>=0.28.1
pydantic>=2.10.0
python-dotenv>=1.0.1
`;

  // 2. pyproject.toml
  files['pyproject.toml'] = `[project]
name = "${serverName}"
version = "${spec.version || '1.0.0'}"
description = "${spec.description || 'Standalone FastMCP server generated by PostMCP'}"
requires-python = ">=3.10"
dependencies = [
    "mcp>=1.2.0",
    "httpx>=0.28.1",
    "pydantic>=2.10.0",
    "python-dotenv>=1.0.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
`;

  // 3. server.py
  const toolFunctions: string[] = [];

  for (const op of spec.operations) {
    const fnName = pythonIdentifier(op.id);
    const summary = (op.summary || '').replace(/"/g, '\\"');
    const desc = (op.description || summary).replace(/"/g, '\\"');
    const endpointPath = op.path;
    const method = op.method.toUpperCase();

    // Generate parameters
    const paramEntries = Object.entries(op.inputSchema?.properties || {});
    const requiredList = op.inputSchema?.required || [];

    const pyParams: string[] = [];
    for (const [propKey, propSchema] of paramEntries) {
      const isReq = requiredList.includes(propKey);
      const pyType = mapSchemaToPythonType(propSchema);
      const safeParamName = pythonIdentifier(propKey);
      if (isReq) {
        pyParams.push(`${safeParamName}: ${pyType}`);
      } else {
        pyParams.push(`${safeParamName}: ${pyType} = None`);
      }
    }

    const paramArgsStr = pyParams.length > 0 ? pyParams.join(', ') : '';

    toolFunctions.push(`
@mcp.tool(name="${op.id}", description="""${desc}""")
async def ${fnName}(${paramArgsStr}) -> str:
    \"\"\"${summary}\"\"\"
    url = f"{BASE_URL.rstrip('/')}/${endpointPath.replace(/^\//, '')}"
    headers = {"User-Agent": "${serverName}/1.0.0"}
    
    api_key = os.getenv("API_KEY")
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"
        
    query_params = {}
    
    # Collect arguments and interpolate URL placeholders
    args = locals().copy()
    args.pop("url", None)
    args.pop("headers", None)
    args.pop("query_params", None)
    args.pop("api_key", None)
    
    for k, v in args.items():
        if v is not None:
            placeholder = f"{{{k}}}"
            if placeholder in url:
                url = url.replace(placeholder, str(v))
            else:
                query_params[k] = v
                
    async with httpx.AsyncClient(timeout=30.0) as client:
        try:
            resp = await client.request("${method}", url, params=query_params, headers=headers)
            if resp.is_error:
                return f"[HTTP {resp.status_code}] {resp.text}"
            return resp.text
        except Exception as e:
            return f"Error executing request: {str(e)}"
`);
  }

  files['server.py'] = `import os
import httpx
from dotenv import load_dotenv
from mcp.server.fastmcp import FastMCP

load_dotenv()

BASE_URL = os.getenv("BASE_URL", "${baseUrl}")

mcp = FastMCP("${spec.title || 'FastMCP Server'}")

${toolFunctions.join('\n')}

if __name__ == "__main__":
    mcp.run()
`;

  // 4. README.md
  files['README.md'] = `# ${spec.title} - FastMCP Server

Standalone Python Model Context Protocol (MCP) server generated by **[PostMCP](https://github.com/BraveRam/postmcp)**.

## Quick Start

\`\`\`bash
pip install -r requirements.txt
python server.py
\`\`\`

## Configuration

Set environment variables in your \`.env\` file:

\`\`\`env
BASE_URL=${baseUrl}
API_KEY=your_api_key_here
\`\`\`

## Claude Desktop Configuration

\`\`\`json
{
  "mcpServers": {
    "${serverName}": {
      "command": "python",
      "args": ["${path.join(process.cwd(), 'server.py')}"],
      "env": {
        "BASE_URL": "${baseUrl}",
        "API_KEY": "your_api_key_here"
      }
    }
  }
}
\`\`\`
`;

  return { files };
}
