import * as path from 'node:path';
import { NormalizedSpec, NormalizedOperation } from '@postmcp/core';
import { GeneratedProject } from './types.js';

export { GeneratedProject };

function sanitizeIdentifier(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, '_');
}

export function generateTypeScriptProject(spec: NormalizedSpec): GeneratedProject {
  const files: Record<string, string> = {};

  const serverName = spec.title.toLowerCase().replace(/[^a-z0-9]/g, '-') || 'mcp-server';
  const baseUrl = spec.servers.length > 0 ? spec.servers[0].url : 'https://api.example.com';

  // 1. package.json
  files['package.json'] = JSON.stringify(
    {
      name: serverName,
      version: spec.version || '1.0.0',
      description: spec.description || `Standalone MCP server generated by PostMCP for ${spec.title}`,
      type: 'module',
      main: './dist/index.js',
      bin: {
        [serverName]: './dist/index.js',
      },
      scripts: {
        build: 'tsc',
        start: 'node ./dist/index.js',
        dev: 'tsc -w',
      },
      dependencies: {
        '@modelcontextprotocol/sdk': '^1.6.1',
        axios: '^1.7.9',
        zod: '^3.24.2',
        dotenv: '^16.4.7',
      },
      devDependencies: {
        '@types/node': '^22.13.5',
        typescript: '^5.7.3',
      },
    },
    null,
    2
  );

  // 2. tsconfig.json
  files['tsconfig.json'] = JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'NodeNext',
        moduleResolution: 'NodeNext',
        outDir: './dist',
        rootDir: './src',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
      },
      include: ['src/**/*'],
    },
    null,
    2
  );

  // 3. src/index.ts
  const toolDefinitions: string[] = [];

  for (const op of spec.operations) {
    const fnName = sanitizeIdentifier(op.id);
    const summary = (op.summary || '').replace(/`/g, '\\`');
    const desc = (op.description || summary).replace(/`/g, '\\`');
    const endpointPath = op.path;
    const method = op.method.toUpperCase();

    toolDefinitions.push(`
  // Tool: ${op.id} (${method} ${endpointPath})
  server.tool(
    '${op.id}',
    \`${desc || summary}\`,
    ${JSON.stringify(op.inputSchema?.properties || {}, null, 4)},
    async (args) => {
      try {
        let targetPath = '${endpointPath}';
        const queryParams: Record<string, any> = {};
        const headers: Record<string, string> = {
          'User-Agent': '${serverName}/1.0.0',
        };

        // Attach Authorization if configured in environment
        if (process.env.API_KEY) {
          headers['Authorization'] = \`Bearer \${process.env.API_KEY}\`;
        }

        // Interpolate path parameters
        for (const [k, v] of Object.entries(args)) {
          if (targetPath.includes(\`{\${k}}\`)) {
            targetPath = targetPath.replaceAll(\`{\${k}}\`, encodeURIComponent(String(v)));
          } else {
            queryParams[k] = v;
          }
        }

        const url = \`\${BASE_URL.replace(/\\/$/, '')}/\${targetPath.replace(/^\\//, '')}\`;
        const response = await axios({
          method: '${method}',
          url,
          params: queryParams,
          headers,
          validateStatus: () => true,
        });

        const isError = response.status >= 400;
        const resultText = typeof response.data === 'object' ? JSON.stringify(response.data, null, 2) : String(response.data);

        return {
          content: [
            {
              type: 'text',
              text: isError ? \`[HTTP \${response.status}] \${resultText}\` : resultText,
            },
          ],
          isError,
        };
      } catch (err: any) {
        return {
          content: [{ type: 'text', text: \`Request failed: \${err.message}\` }],
          isError: true,
        };
      }
    }
  );`);
  }

  files['src/index.ts'] = `import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import axios from 'axios';
import dotenv from 'dotenv';

dotenv.config();

const BASE_URL = process.env.BASE_URL || '${baseUrl}';

const server = new McpServer({
  name: '${serverName}',
  version: '${spec.version || '1.0.0'}',
});

// Register Generated Tools
${toolDefinitions.join('\n')}

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error('${serverName} MCP server running on stdio');
}

main().catch((err) => {
  console.error('Fatal server error:', err);
  process.exit(1);
});
`;

  // 4. README.md
  files['README.md'] = `# ${spec.title} - MCP Server

Standalone Model Context Protocol (MCP) server generated by **[PostMCP](https://github.com/BraveRam/postmcp)**.

## Quick Start

\`\`\`bash
npm install
npm run build
npm start
\`\`\`

## Configuration

Set environment variables in your \`.env\` file:

\`\`\`env
BASE_URL=${baseUrl}
API_KEY=your_api_key_here
\`\`\`

## Claude Desktop Configuration

Add this to your \`claude_desktop_config.json\`:

\`\`\`json
{
  "mcpServers": {
    "${serverName}": {
      "command": "node",
      "args": ["${path.join(process.cwd(), 'dist', 'index.js')}"],
      "env": {
        "BASE_URL": "${baseUrl}",
        "API_KEY": "your_api_key_here"
      }
    }
  }
}
\`\`\`
`;

  return { files };
}
