import { NormalizedSpec, NormalizedOperation, GeneratedProject } from '@postmcp/types';

function pythonIdentifier(name: string): string {
  const s = name
    .replace(/([A-Z])/g, '_$1')
    .toLowerCase()
    .replace(/[^a-z0-9_]/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '');
  return s || 'tool_func';
}

function mapSchemaToPythonType(schema: any): string {
  if (!schema || !schema.type) return 'str';
  if (schema.type === 'integer') return 'int';
  if (schema.type === 'number') return 'float';
  if (schema.type === 'boolean') return 'bool';
  if (schema.type === 'array') return 'list';
  if (schema.type === 'object') return 'dict';
  return 'str';
}

export function generatePythonProject(spec: NormalizedSpec): GeneratedProject {
  const files: Record<string, string> = {};

  const serverName = spec.title.toLowerCase().replace(/[^a-z0-9]/g, '_') || 'mcp_server';
  const baseUrl = spec.servers.length > 0 ? spec.servers[0].url : 'https://api.example.com';

  // 1. requirements.txt
  files['requirements.txt'] = `mcp[cli]>=1.3.0
httpx>=0.28.1
pydantic>=2.10.0
python-dotenv>=1.0.1
`;

  // 2. pyproject.toml
  files['pyproject.toml'] = `[project]
name = "${serverName}"
version = "${spec.version || '1.0.0'}"
description = "${spec.description || 'Standalone FastMCP server generated by PostMCP'}"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.3.0",
    "httpx>=0.28.1",
    "pydantic>=2.10.0",
    "python-dotenv>=1.0.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
`;

  // 3. server.py
  const toolFunctions: string[] = [];

  for (const op of spec.operations) {
    const fnName = pythonIdentifier(op.id);
    const docstring = (op.description || op.summary || `Execute ${op.id}`).replace(/"""/g, '\\"\\"\\"');

    // Build parameter arguments
    const paramsList: string[] = [];
    const queryParamPushes: string[] = [];
    const pathParamReplacements: string[] = [];
    let hasBody = false;

    if (op.parameters) {
      for (const p of op.parameters) {
        const pyName = pythonIdentifier(p.name);
        const pyType = mapSchemaToPythonType(p.schema);
        const isRequired = p.required;

        if (isRequired) {
          paramsList.push(`${pyName}: ${pyType}`);
        } else {
          paramsList.push(`${pyName}: ${pyType} | None = None`);
        }

        if (p.in === 'path') {
          pathParamReplacements.push(`url = url.replace("{${p.name}}", str(${pyName}))`);
        } else if (p.in === 'query') {
          queryParamPushes.push(`if ${pyName} is not None:\n        params["${p.name}"] = ${pyName}`);
        } else if (p.in === 'body') {
          hasBody = true;
        }
      }
    }

    if (op.inputSchema && op.inputSchema.properties && paramsList.length === 0) {
      for (const [propName, propSchema] of Object.entries<any>(op.inputSchema.properties)) {
        const pyName = pythonIdentifier(propName);
        const pyType = mapSchemaToPythonType(propSchema);
        const isRequired = (op.inputSchema.required || []).includes(propName);

        if (isRequired) {
          paramsList.push(`${pyName}: ${pyType}`);
        } else {
          paramsList.push(`${pyName}: ${pyType} | None = None`);
        }
      }
      hasBody = true;
    }

    const pathReplacementsStr =
      pathParamReplacements.length > 0 ? '\n    ' + pathParamReplacements.join('\n    ') : '';
    const queryParamsStr =
      queryParamPushes.length > 0 ? '\n    ' + queryParamPushes.join('\n    ') : '';

    const bodyPayloadStr = hasBody
      ? `\n    # Request body payload\n    body_data = {}\n    for k, v in locals().items():\n        if k not in ["client", "url", "params", "headers", "res"] and v is not None:\n            body_data[k] = v\n`
      : '';

    const httpRequestStr = `
    async with httpx.AsyncClient(base_url=BASE_URL, headers=headers, timeout=30.0) as client:
        url = "${op.path}"${pathReplacementsStr}
        params = {}${queryParamsStr}${bodyPayloadStr}
        res = await client.request(
            "${op.method.toUpperCase()}",
            url,
            params=params if params else None,
            ${hasBody ? 'json=body_data if body_data else None' : 'None'},
        )
        res.raise_for_status()
        data = res.json() if res.headers.get("content-type", "").startswith("application/json") else res.text
        return format_token_diet(data)
`;

    toolFunctions.push(`
@mcp.tool()
async def ${fnName}(${paramsList.join(', ')}) -> str:
    """${docstring}"""
${httpRequestStr}`);
  }

  files['server.py'] = `"""
${spec.title} - FastMCP Server
Generated automatically by PostMCP (The Postman for MCP)
"""

import os
import json
from dotenv import load_dotenv
import httpx
from mcp.server.fastmcp import FastMCP

load_dotenv()

BASE_URL = os.getenv("BASE_URL", "${baseUrl}").rstrip("/")
API_KEY = os.getenv("API_KEY", os.getenv("BEARER_TOKEN", ""))

mcp = FastMCP("${spec.title}")

headers = {
    "User-Agent": "PostMCP-FastMCP/1.0",
    "Accept": "application/json",
}
if API_KEY:
    headers["Authorization"] = f"Bearer {API_KEY}"

def format_token_diet(data) -> str:
    """Format JSON responses efficiently for LLM context."""
    if isinstance(data, list) and len(data) > 0 and isinstance(data[0], dict):
        # Format as Markdown Table for high context efficiency
        keys = list(data[0].keys())[:8] # Top fields
        header_row = "| " + " | ".join(keys) + " |"
        sep_row = "| " + " | ".join(["---"] * len(keys)) + " |"
        rows = [header_row, sep_row]
        for item in data[:25]:
            rows.append("| " + " | ".join(str(item.get(k, "")).replace("\\n", " ") for k in keys) + " |")
        return "\\n".join(rows)
    if isinstance(data, (dict, list)):
        return json.dumps(data, indent=2)
    return str(data)
${toolFunctions.join('\n')}

if __name__ == "__main__":
    mcp.run()
`;

  // 4. README.md
  files['README.md'] = `# ${spec.title} MCP Server (Python FastMCP)

Standalone Model Context Protocol (MCP) server generated by **PostMCP** for **${spec.title}**.

## Prerequisites
- Python 3.10+
- [uv](https://docs.astral.sh/uv/) (recommended) or \`pip\`

## Quick Start

### 1. Install Dependencies
\`\`\`bash
# With uv (recommended)
uv sync

# Or with pip
pip install -r requirements.txt
\`\`\`

### 2. Configure Environment Variables
Copy \`.env.example\` to \`.env\` and fill in your API credentials:
\`\`\`bash
cp .env.example .env
\`\`\`

### 3. Run the MCP Server
\`\`\`bash
# Direct execution (stdio transport)
python server.py
# Or with uv
uv run server.py
\`\`\`

### 4. Test with MCP Inspector
\`\`\`bash
uv run mcp dev server.py
\`\`\`

### 5. Install to Claude Desktop
\`\`\`bash
uv run mcp install server.py
\`\`\`
`;

  // 5. .env.example
  files['.env.example'] = `BASE_URL=${baseUrl}
API_KEY=your_api_key_here
`;

  // 6. .gitignore
  files['.gitignore'] = `__pycache__/
*.py[cod]
*$py.class
.venv/
venv/
.env
.DS_Store
`;

  return { files };
}
