import { NormalizedSpec, NormalizedOperation, GeneratedProject } from '@postmcp/types';

export function sanitizeIdentifier(name: string): string {
  let s = name.replace(/[^a-zA-Z0-9_]/g, '_');
  if (/^[0-9]/.test(s)) {
    s = `_${s}`;
  }
  return s || 'tool';
}

export function convertSchemaToZod(schema: any, depth: number = 0): string {
  if (!schema || depth > 8) {
    return 'z.any()';
  }

  // 1. Enum types
  if (schema.enum && Array.isArray(schema.enum) && schema.enum.length > 0) {
    const isAllStrings = schema.enum.every((v: any) => typeof v === 'string');
    if (isAllStrings) {
      const literals = schema.enum.map((v: any) => JSON.stringify(v)).join(', ');
      let zod = `z.enum([${literals}])`;
      if (schema.description) zod += `.describe(${JSON.stringify(schema.description)})`;
      return zod;
    }
    // Numeric, boolean, or mixed enums require z.literal / z.union
    if (schema.enum.length === 1) {
      let zod = `z.literal(${JSON.stringify(schema.enum[0])})`;
      if (schema.description) zod += `.describe(${JSON.stringify(schema.description)})`;
      return zod;
    }
    const literals = schema.enum.map((v: any) => `z.literal(${JSON.stringify(v)})`).join(', ');
    let zod = `z.union([${literals}])`;
    if (schema.description) zod += `.describe(${JSON.stringify(schema.description)})`;
    return zod;
  }

  // 2. Primitive types
  if (schema.type === 'string') {
    let zod = 'z.string()';
    if (schema.format === 'email') zod += '.email()';
    if (schema.format === 'uuid') zod += '.uuid()';
    if (schema.format === 'url' || schema.format === 'uri') zod += '.url()';
    if (typeof schema.minLength === 'number') zod += `.min(${schema.minLength})`;
    if (typeof schema.maxLength === 'number') zod += `.max(${schema.maxLength})`;
    if (schema.description) zod += `.describe(${JSON.stringify(schema.description)})`;
    return zod;
  }

  if (schema.type === 'integer' || schema.type === 'number') {
    let zod = schema.type === 'integer' ? 'z.number().int()' : 'z.number()';
    if (typeof schema.minimum === 'number') zod += `.min(${schema.minimum})`;
    if (typeof schema.maximum === 'number') zod += `.max(${schema.maximum})`;
    if (schema.description) zod += `.describe(${JSON.stringify(schema.description)})`;
    return zod;
  }

  if (schema.type === 'boolean') {
    let zod = 'z.boolean()';
    if (schema.description) zod += `.describe(${JSON.stringify(schema.description)})`;
    return zod;
  }

  // 3. Array types
  if (schema.type === 'array') {
    const itemZod = schema.items ? convertSchemaToZod(schema.items, depth + 1) : 'z.any()';
    let zod = `z.array(${itemZod})`;
    if (typeof schema.minItems === 'number') zod += `.min(${schema.minItems})`;
    if (typeof schema.maxItems === 'number') zod += `.max(${schema.maxItems})`;
    if (schema.description) zod += `.describe(${JSON.stringify(schema.description)})`;
    return zod;
  }

  // 4. Object types with nested properties
  if (schema.type === 'object' || schema.properties) {
    const props = schema.properties || {};
    const requiredSet = new Set(Array.isArray(schema.required) ? schema.required : []);
    const shapeEntries: string[] = [];

    for (const [key, propSchema] of Object.entries<any>(props)) {
      const isReq = requiredSet.has(key);
      const innerZod = convertSchemaToZod(propSchema, depth + 1);
      const fieldZod = isReq ? innerZod : `${innerZod}.optional()`;
      shapeEntries.push(`    ${JSON.stringify(key)}: ${fieldZod}`);
    }

    if (shapeEntries.length === 0) {
      return schema.additionalProperties
        ? `z.record(z.string(), ${convertSchemaToZod(schema.additionalProperties, depth + 1)})`
        : 'z.record(z.string(), z.any())';
    }

    let zod = `z.object({\n${shapeEntries.join(',\n')}\n  })`;
    if (schema.description) zod += `.describe(${JSON.stringify(schema.description)})`;
    return zod;
  }

  // 5. Unions (oneOf / anyOf)
  if (schema.oneOf && Array.isArray(schema.oneOf) && schema.oneOf.length > 0) {
    const members = schema.oneOf.map((m: any) => convertSchemaToZod(m, depth + 1));
    return `z.union([${members.join(', ')}])`;
  }
  if (schema.anyOf && Array.isArray(schema.anyOf) && schema.anyOf.length > 0) {
    const members = schema.anyOf.map((m: any) => convertSchemaToZod(m, depth + 1));
    return `z.union([${members.join(', ')}])`;
  }

  return 'z.any()';
}

export function generateTypeScriptProject(spec: NormalizedSpec): GeneratedProject {
  const files: Record<string, string> = {};

  const serverName =
    spec.title
      .toLowerCase()
      .replace(/[^a-z0-9]/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '') || 'mcp-server';
  const baseUrl = spec.servers.length > 0 ? spec.servers[0].url : 'https://api.example.com';

  // 1. package.json
  files['package.json'] = JSON.stringify(
    {
      name: serverName,
      version: spec.version || '1.0.0',
      description: spec.description || `Standalone MCP server generated by PostMCP for ${spec.title}`,
      type: 'module',
      main: './dist/index.js',
      bin: {
        [serverName]: './dist/index.js',
      },
      scripts: {
        build: 'tsc',
        start: 'node ./dist/index.js',
        dev: 'tsx src/index.ts',
      },
      dependencies: {
        '@modelcontextprotocol/sdk': '^1.6.1',
        axios: '^1.7.9',
        zod: '^3.24.2',
        dotenv: '^16.4.7',
      },
      devDependencies: {
        '@types/node': '^22.13.5',
        tsx: '^4.19.2',
        typescript: '^5.7.3',
      },
    },
    null,
    2
  );

  // 2. tsconfig.json
  files['tsconfig.json'] = JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'NodeNext',
        moduleResolution: 'NodeNext',
        outDir: './dist',
        rootDir: './src',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
      },
      include: ['src/**/*'],
    },
    null,
    2
  );

  // 3. src/index.ts
  const toolRegistrations: string[] = [];

  for (const op of spec.operations) {
    const toolId = op.id;
    const description = op.description || op.summary || `Execute ${op.id}`;

    // Collect all parameters
    const pathParams: { name: string; schema: any; required: boolean }[] = [];
    const queryParams: { name: string; schema: any; required: boolean }[] = [];
    const headerParams: { name: string; schema: any; required: boolean }[] = [];
    const cookieParams: { name: string; schema: any; required: boolean }[] = [];
    const bodyProps: { name: string; schema: any; required: boolean }[] = [];
    let isDirectBody = false;
    let directBodyPropName: string | null = null;

    const schemaFields: string[] = [];

    if (op.parameters) {
      for (const p of op.parameters) {
        const isReq = !!p.required;
        const zodCode = convertSchemaToZod(p.schema);
        const fieldZod = isReq ? zodCode : `${zodCode}.optional()`;
        schemaFields.push(`    ${JSON.stringify(p.name)}: ${fieldZod},`);

        if (p.in === 'path') {
          pathParams.push({ name: p.name, schema: p.schema, required: isReq });
        } else if (p.in === 'header') {
          headerParams.push({ name: p.name, schema: p.schema, required: isReq });
        } else if (p.in === 'cookie') {
          cookieParams.push({ name: p.name, schema: p.schema, required: isReq });
        } else {
          queryParams.push({ name: p.name, schema: p.schema, required: isReq });
        }
      }
    }

    // Merge request body properties
    if (op.inputSchema && op.inputSchema.properties) {
      const knownParamNames = new Set((op.parameters || []).map((p) => p.name));
      const requiredBodySet = new Set(Array.isArray(op.inputSchema.required) ? op.inputSchema.required : []);
      const nonParamEntries = Object.entries<any>(op.inputSchema.properties).filter(([k]) => !knownParamNames.has(k));

      // Check if this is a direct single primitive/array body property named 'requestBody' or 'body'
      if (
        nonParamEntries.length === 1 &&
        (nonParamEntries[0][0] === 'requestBody' || nonParamEntries[0][0] === 'body') &&
        (nonParamEntries[0][1].type !== 'object' || !nonParamEntries[0][1].properties)
      ) {
        const [propName, propSchema] = nonParamEntries[0];
        const isReq = requiredBodySet.has(propName);
        const zodCode = convertSchemaToZod(propSchema);
        const fieldZod = isReq ? zodCode : `${zodCode}.optional()`;
        schemaFields.push(`    ${JSON.stringify(propName)}: ${fieldZod},`);
        isDirectBody = true;
        directBodyPropName = propName;
      } else {
        for (const [propName, propSchema] of nonParamEntries) {
          const isReq = requiredBodySet.has(propName);
          const zodCode = convertSchemaToZod(propSchema);
          const fieldZod = isReq ? zodCode : `${zodCode}.optional()`;
          schemaFields.push(`    ${JSON.stringify(propName)}: ${fieldZod},`);
          bodyProps.push({ name: propName, schema: propSchema, required: isReq });
        }
      }
    }

    // Generate tool execution logic
    const executionLines: string[] = [];
    executionLines.push(`    try {`);
    executionLines.push('      if (DRY_RUN) {');
    executionLines.push(`        return { content: [{ type: 'text', text: \`[DRY-RUN] Simulating \${${JSON.stringify(op.method.toUpperCase())}} \${${JSON.stringify(op.path)}} (\${${JSON.stringify(op.riskTier || 'READ_ONLY')}})\` }] };`);
    executionLines.push('      }');

    executionLines.push(`      let url = ${JSON.stringify(op.path)};`);

    for (const p of pathParams) {
      executionLines.push(`      url = url.replace("{${p.name}}", encodeURIComponent(String(args[${JSON.stringify(p.name)}])));`);
    }

    if (queryParams.length > 0) {
      executionLines.push('      const query: Record<string, any> = {};');
      for (const p of queryParams) {
        executionLines.push(`      if (args[${JSON.stringify(p.name)}] !== undefined) query[${JSON.stringify(p.name)}] = args[${JSON.stringify(p.name)}];`);
      }
    }

    if (headerParams.length > 0 || cookieParams.length > 0) {
      executionLines.push('      const reqHeaders: Record<string, string> = {};');
      for (const p of headerParams) {
        executionLines.push(`      if (args[${JSON.stringify(p.name)}] !== undefined) reqHeaders[${JSON.stringify(p.name)}] = String(args[${JSON.stringify(p.name)}]);`);
      }
      if (cookieParams.length > 0) {
        executionLines.push('      const cookieParts: string[] = [];');
        for (const p of cookieParams) {
          executionLines.push(`      if (args[${JSON.stringify(p.name)}] !== undefined) cookieParts.push(\`\${${JSON.stringify(p.name)}}=\${encodeURIComponent(String(args[${JSON.stringify(p.name)}]))}\`);`);
        }
        executionLines.push("      if (cookieParts.length > 0) reqHeaders['Cookie'] = cookieParts.join('; ');");
      }
    }

    if (isDirectBody && directBodyPropName) {
      executionLines.push(`      const bodyData = args[${JSON.stringify(directBodyPropName)}];`);
    } else if (bodyProps.length > 0) {
      executionLines.push('      const bodyData: Record<string, any> = {};');
      for (const p of bodyProps) {
        executionLines.push(`      if (args[${JSON.stringify(p.name)}] !== undefined) bodyData[${JSON.stringify(p.name)}] = args[${JSON.stringify(p.name)}];`);
      }
    }

    const queryArg = queryParams.length > 0 ? 'params: Object.keys(query).length > 0 ? query : undefined,' : '';
    const bodyArg = (isDirectBody && directBodyPropName)
      ? 'data: bodyData !== undefined ? bodyData : undefined,'
      : bodyProps.length > 0
      ? 'data: Object.keys(bodyData).length > 0 ? bodyData : undefined,'
      : '';
    const headerArg = (headerParams.length > 0 || cookieParams.length > 0) ? 'headers: reqHeaders,' : '';

    toolRegistrations.push(`
// Tool: ${JSON.stringify(toolId)}
server.tool(
  ${JSON.stringify(toolId)},
  ${JSON.stringify(description)},
  {
${schemaFields.join('\n')}
  },
  async (args: any) => {
${executionLines.join('\n')}

      const res = await httpClient.request({
        url,
        method: ${JSON.stringify(op.method.toUpperCase())},
        ${queryArg}
        ${bodyArg}
        ${headerArg}
      });

      const formatted = formatTokenDiet(res.data);
      return {
        content: [{ type: 'text', text: formatted }],
      };
    } catch (err: any) {
      const msg = err.response?.data ? JSON.stringify(err.response.data) : err.message;
      return {
        isError: true,
        content: [{ type: 'text', text: \`Error executing \${${JSON.stringify(toolId)}}: \${msg}\` }],
      };
    }
  }
);`);
  }

  // Detect security schemes (Bearer, ApiKey header, Basic)
  const secSchemes = spec.securitySchemes || {};
  const primaryScheme = Object.values(secSchemes)[0] as any;
  let authHeaderCode = '';
  if (primaryScheme) {
    if (primaryScheme.type === 'http' && primaryScheme.scheme === 'bearer') {
      authHeaderCode = `...(API_KEY ? { 'Authorization': \`Bearer \${API_KEY}\` } : {}),`;
    } else if (primaryScheme.type === 'apiKey' && primaryScheme.in === 'header') {
      authHeaderCode = `...(API_KEY ? { ${JSON.stringify(primaryScheme.name)}: API_KEY } : {}),`;
    } else if (primaryScheme.type === 'http' && primaryScheme.scheme === 'basic') {
      authHeaderCode = `...(API_KEY ? { 'Authorization': \`Basic \${Buffer.from(API_KEY).toString('base64')}\` } : {}),`;
    }
  }
  if (!authHeaderCode) {
    authHeaderCode = `...(API_KEY ? { 'Authorization': \`Bearer \${API_KEY}\` } : {}),`;
  }

  files['src/index.ts'] = `/**
 * ${spec.title} - Standalone TypeScript MCP Server
 * Generated automatically by PostMCP (The Postman for MCP)
 */

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import axios from 'axios';
import { z } from 'zod';
import dotenv from 'dotenv';

dotenv.config();

const BASE_URL = (process.env.BASE_URL || ${JSON.stringify(baseUrl)}).replace(/\\/$/, '');
const API_KEY = process.env.API_KEY || process.env.BEARER_TOKEN || '';
const DRY_RUN = process.env.DRY_RUN === 'true';

const httpClient = axios.create({
  baseURL: BASE_URL,
  timeout: 30000,
  headers: {
    'User-Agent': 'PostMCP-TypeScript/1.0',
    'Accept': 'application/json',
    ${authHeaderCode}
  },
});

function formatTokenDiet(data: any): string {
  if (Array.isArray(data) && data.length > 0 && typeof data[0] === 'object' && data[0] !== null) {
    const keys = Object.keys(data[0]).slice(0, 8);
    const headerRow = '| ' + keys.join(' | ') + ' |';
    const sepRow = '| ' + keys.map(() => '---').join(' | ') + ' |';
    const rows = [headerRow, sepRow];
    for (const item of data.slice(0, 25)) {
      rows.push('| ' + keys.map(k => String(item[k] ?? '').replace(/\\n/g, ' ')).join(' | ') + ' |');
    }
    return rows.join('\\n');
  }
  if (typeof data === 'object' && data !== null) {
    return JSON.stringify(data, null, 2);
  }
  return String(data);
}

const server = new McpServer({
  name: ${JSON.stringify(spec.title)},
  version: ${JSON.stringify(spec.version || '1.0.0')},
});
${toolRegistrations.join('\n')}

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error(\`\${${JSON.stringify(spec.title)}} MCP Server running on stdio\`);
}

main().catch((err) => {
  console.error('Fatal server error:', err);
  process.exit(1);
});
`;

  // 4. README.md
  files['README.md'] = `# ${spec.title} MCP Server (TypeScript MCP SDK)

Standalone Model Context Protocol (MCP) server generated by **PostMCP** for **${spec.title}**.

## Prerequisites
- Node.js 20+

## Quick Start

### 1. Install Dependencies
\`\`\`bash
npm install
\`\`\`

### 2. Configure Environment Variables
Copy \`.env.example\` to \`.env\` and add your API credentials:
\`\`\`bash
cp .env.example .env
\`\`\`

### 3. Build & Run
\`\`\`bash
# Development mode
npm run dev

# Production build & run
npm run build
npm start
\`\`\`

### 4. Test with MCP Inspector
\`\`\`bash
npx @modelcontextprotocol/inspector node dist/index.js
\`\`\`
`;

  // 5. .env.example
  files['.env.example'] = `BASE_URL=${baseUrl}
API_KEY=your_api_key_here
DRY_RUN=false
`;

  // 6. .gitignore
  files['.gitignore'] = `node_modules/
dist/
.env
.DS_Store
*.log
`;

  return { files };
}
