import { NormalizedSpec, NormalizedOperation, GeneratedProject } from '@postmcp/types';

function sanitizeIdentifier(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, '_');
}

function mapSchemaToZod(schema: any): string {
  if (!schema) return 'z.string()';
  if (schema.type === 'string') return 'z.string()';
  if (schema.type === 'integer' || schema.type === 'number') return 'z.number()';
  if (schema.type === 'boolean') return 'z.boolean()';
  if (schema.type === 'array') return 'z.array(z.any())';
  if (schema.type === 'object') return 'z.record(z.any())';
  return 'z.any()';
}

export function generateTypeScriptProject(spec: NormalizedSpec): GeneratedProject {
  const files: Record<string, string> = {};

  const serverName = spec.title.toLowerCase().replace(/[^a-z0-9]/g, '-') || 'mcp-server';
  const baseUrl = spec.servers.length > 0 ? spec.servers[0].url : 'https://api.example.com';

  // 1. package.json
  files['package.json'] = JSON.stringify(
    {
      name: serverName,
      version: spec.version || '1.0.0',
      description: spec.description || `Standalone MCP server generated by PostMCP for ${spec.title}`,
      type: 'module',
      main: './dist/index.js',
      bin: {
        [serverName]: './dist/index.js',
      },
      scripts: {
        build: 'tsc',
        start: 'node ./dist/index.js',
        dev: 'tsx src/index.ts',
      },
      dependencies: {
        '@modelcontextprotocol/server': '^1.0.0',
        '@modelcontextprotocol/node': '^1.0.0',
        axios: '^1.7.9',
        zod: '^3.24.2',
        dotenv: '^16.4.7',
      },
      devDependencies: {
        '@types/node': '^22.13.5',
        tsx: '^4.19.2',
        typescript: '^5.7.3',
      },
    },
    null,
    2
  );

  // 2. tsconfig.json
  files['tsconfig.json'] = JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'NodeNext',
        moduleResolution: 'NodeNext',
        outDir: './dist',
        rootDir: './src',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
      },
      include: ['src/**/*'],
    },
    null,
    2
  );

  // 3. src/index.ts
  const toolRegistrations: string[] = [];

  for (const op of spec.operations) {
    const toolId = op.id;
    const description = (op.description || op.summary || `Execute ${op.id}`).replace(/'/g, "\\'");

    // Build Zod schema shape
    const zodFields: string[] = [];
    const pathReplacements: string[] = [];
    const queryParams: string[] = [];
    let hasBody = false;

    if (op.parameters) {
      for (const p of op.parameters) {
        const isRequired = p.required;
        const baseZod = mapSchemaToZod(p.schema);
        const zodDef = isRequired ? baseZod : `${baseZod}.optional()`;
        zodFields.push(`  ${p.name}: ${zodDef},`);

        if (p.in === 'path') {
          pathReplacements.push(`url = url.replace('{${p.name}}', encodeURIComponent(String(args['${p.name}'])));`);
        } else if (p.in === 'query') {
          queryParams.push(`if (args['${p.name}'] !== undefined) query['${p.name}'] = args['${p.name}'];`);
        } else if (p.in === 'body') {
          hasBody = true;
        }
      }
    }

    if (op.inputSchema && op.inputSchema.properties && zodFields.length === 0) {
      for (const [propName, propSchema] of Object.entries<any>(op.inputSchema.properties)) {
        const isRequired = (op.inputSchema.required || []).includes(propName);
        const baseZod = mapSchemaToZod(propSchema);
        const zodDef = isRequired ? baseZod : `${baseZod}.optional()`;
        zodFields.push(`  ${propName}: ${zodDef},`);
      }
      hasBody = true;
    }

    const pathReplacementsCode =
      pathReplacements.length > 0 ? '\n      ' + pathReplacements.join('\n      ') : '';
    const queryParamsCode = queryParams.length > 0 ? '\n      ' + queryParams.join('\n      ') : '';

    const bodyCode = hasBody
      ? `\n      const bodyData: Record<string, any> = {};\n      for (const [k, v] of Object.entries(args)) {\n        if (v !== undefined) bodyData[k] = v;\n      }`
      : '';

    toolRegistrations.push(`
// Tool: ${toolId}
server.registerTool(
  '${toolId}',
  {
    description: '${description}',
    inputSchema: z.object({
${zodFields.join('\n')}
    }),
  },
  async (args, ctx) => {
    try {
      let url = '${op.path}';${pathReplacementsCode}
      const query: Record<string, any> = {};${queryParamsCode}${bodyCode}

      const res = await httpClient.request({
        url,
        method: '${op.method.toUpperCase()}',
        params: Object.keys(query).length > 0 ? query : undefined,
        data: ${hasBody ? 'Object.keys(bodyData).length > 0 ? bodyData : undefined' : 'undefined'},
      });

      const formatted = formatTokenDiet(res.data);
      return {
        content: [{ type: 'text', text: formatted }],
      };
    } catch (err: any) {
      const msg = err.response?.data ? JSON.stringify(err.response.data) : err.message;
      return {
        isError: true,
        content: [{ type: 'text', text: \`Error executing ${toolId}: \${msg}\` }],
      };
    }
  }
);`);
  }

  files['src/index.ts'] = `/**
 * ${spec.title} - Standalone TypeScript MCP Server (MCP SDK v2)
 * Generated automatically by PostMCP (The Postman for MCP)
 */

import { McpServer } from '@modelcontextprotocol/server';
import { StdioServerTransport } from '@modelcontextprotocol/server/stdio';
import axios from 'axios';
import { z } from 'zod';
import dotenv from 'dotenv';

dotenv.config();

const BASE_URL = (process.env.BASE_URL || '${baseUrl}').replace(/\\/$/, '');
const API_KEY = process.env.API_KEY || process.env.BEARER_TOKEN || '';

const httpClient = axios.create({
  baseURL: BASE_URL,
  timeout: 30000,
  headers: {
    'User-Agent': 'PostMCP-TypeScript/1.0',
    'Accept': 'application/json',
    ...(API_KEY ? { 'Authorization': \`Bearer \${API_KEY}\` } : {}),
  },
});

function formatTokenDiet(data: any): string {
  if (Array.isArray(data) && data.length > 0 && typeof data[0] === 'object' && data[0] !== null) {
    const keys = Object.keys(data[0]).slice(0, 8);
    const headerRow = '| ' + keys.join(' | ') + ' |';
    const sepRow = '| ' + keys.map(() => '---').join(' | ') + ' |';
    const rows = [headerRow, sepRow];
    for (const item of data.slice(0, 25)) {
      rows.push('| ' + keys.map(k => String(item[k] ?? '').replace(/\\n/g, ' ')).join(' | ') + ' |');
    }
    return rows.join('\\n');
  }
  if (typeof data === 'object' && data !== null) {
    return JSON.stringify(data, null, 2);
  }
  return String(data);
}

const server = new McpServer({
  name: '${spec.title}',
  version: '${spec.version || '1.0.0'}',
});
${toolRegistrations.join('\n')}

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error('${spec.title} MCP Server running on stdio');
}

main().catch((err) => {
  console.error('Fatal server error:', err);
  process.exit(1);
});
`;

  // 4. README.md
  files['README.md'] = `# ${spec.title} MCP Server (TypeScript MCP SDK v2)

Standalone Model Context Protocol (MCP) server generated by **PostMCP** for **${spec.title}**.

## Prerequisites
- Node.js 20+

## Quick Start

### 1. Install Dependencies
\`\`\`bash
npm install
\`\`\`

### 2. Configure Environment Variables
Copy \`.env.example\` to \`.env\` and add your API credentials:
\`\`\`bash
cp .env.example .env
\`\`\`

### 3. Build & Run
\`\`\`bash
# Development mode
npm run dev

# Production build & run
npm run build
npm start
\`\`\`

### 4. Test with MCP Inspector
\`\`\`bash
npx @modelcontextprotocol/inspector node dist/index.js
\`\`\`
`;

  // 5. .env.example
  files['.env.example'] = `BASE_URL=${baseUrl}
API_KEY=your_api_key_here
`;

  // 6. .gitignore
  files['.gitignore'] = `node_modules/
dist/
.env
.DS_Store
*.log
`;

  return { files };
}
