import { Preset } from '../types.js';

export const CLOUD_DATABASES_PRESETS: Preset[] = [
  {
    id: 'supabase',
    name: 'Supabase Management API',
    description: 'Create and configure Postgres databases, auth policies, edge functions, and storage buckets.',
    category: 'Database & Cloud',
    authType: 'Bearer (SUPABASE_ACCESS_TOKEN)',
    authEnvVar: 'SUPABASE_ACCESS_TOKEN',
    defaultBaseUrl: 'https://api.supabase.com/v1',
    specUrl: 'https://api.supabase.com/v1/openapi.json',
    tags: ['postgres', 'auth', 'database', 'storage', 'edge-functions', 'baas'],
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare API',
    description: 'Manage DNS records, Cloudflare Workers, KV, R2 storage buckets, and firewall rules.',
    category: 'Database & Cloud',
    authType: 'Bearer (CLOUDFLARE_API_TOKEN)',
    authEnvVar: 'CLOUDFLARE_API_TOKEN',
    defaultBaseUrl: 'https://api.cloudflare.com/client/v4',
    tags: ['cdn', 'dns', 'workers', 'r2', 'kv', 'edge', 'security'],
  },
  {
    id: 'flyio',
    name: 'Fly.io Machines API',
    description: 'Launch and control fast lightweight micro-VMs close to users worldwide.',
    category: 'Database & Cloud',
    authType: 'Bearer (FLY_API_TOKEN)',
    authEnvVar: 'FLY_API_TOKEN',
    defaultBaseUrl: 'https://api.machines.dev/v1',
    tags: ['vms', 'hosting', 'docker', 'containers', 'edge'],
  },
  {
    id: 'railway',
    name: 'Railway API',
    description: 'Deploy full-stack services, provision Postgres/Redis plugins, and manage environment variables.',
    category: 'Database & Cloud',
    authType: 'Bearer (RAILWAY_API_TOKEN)',
    authEnvVar: 'RAILWAY_API_TOKEN',
    defaultBaseUrl: 'https://backboard.railway.app/graphql/v2',
    tags: ['paas', 'hosting', 'deployments', 'databases'],
  },
  {
    id: 'render',
    name: 'Render API',
    description: 'Manage web services, private services, static sites, background workers, and PostgreSQL instances.',
    category: 'Database & Cloud',
    authType: 'Bearer (RENDER_API_KEY)',
    authEnvVar: 'RENDER_API_KEY',
    defaultBaseUrl: 'https://api.render.com/v1',
    tags: ['cloud', 'hosting', 'postgres', 'cron-jobs'],
  },
  {
    id: 'neon',
    name: 'Neon Serverless Postgres API',
    description: 'Serverless branching PostgreSQL databases with instant cold starts and autoscaling.',
    category: 'Database & Cloud',
    authType: 'Bearer (NEON_API_KEY)',
    authEnvVar: 'NEON_API_KEY',
    defaultBaseUrl: 'https://console.neon.tech/api/v2',
    tags: ['postgres', 'serverless', 'branching', 'sql'],
  },
  {
    id: 'upstash',
    name: 'Upstash Serverless Redis & QStash API',
    description: 'Serverless low-latency Redis cache, Vector database, and QStash message queuing.',
    category: 'Database & Cloud',
    authType: 'Bearer (UPSTASH_EMAIL:UPSTASH_API_KEY)',
    authEnvVar: 'UPSTASH_API_KEY',
    defaultBaseUrl: 'https://api.upstash.com/v2',
    tags: ['redis', 'vector', 'queue', 'serverless', 'caching'],
  },
  {
    id: 'planetscale',
    name: 'PlanetScale API',
    description: 'Serverless MySQL platform with zero-downtime schema migrations and branch merging.',
    category: 'Database & Cloud',
    authType: 'Bearer (PLANETSCALE_SERVICE_TOKEN)',
    authEnvVar: 'PLANETSCALE_TOKEN',
    defaultBaseUrl: 'https://api.planetscale.com/v1',
    tags: ['mysql', 'database', 'branching', 'serverless'],
  },
];
