import { Preset } from '../types.js';

export const COMMUNICATION_AI_PRESETS: Preset[] = [
  {
    id: 'resend',
    name: 'Resend Email API',
    description: 'Developer-first transactional email delivery, domains, batch sends, and webhooks.',
    category: 'Communication & AI',
    authType: 'Bearer (RESEND_API_KEY)',
    authEnvVar: 'RESEND_API_KEY',
    defaultBaseUrl: 'https://api.resend.com',
    specUrl: 'https://raw.githubusercontent.com/resend/resend-openapi/main/openapi.json',
    tags: ['email', 'transactional', 'domains', 'deliverability'],
    fieldMasks: [
      { path: '/emails', fields: ['id', 'from', 'to', 'subject', 'created_at'] },
    ],
  },
  {
    id: 'sendgrid',
    name: 'Twilio SendGrid API',
    description: 'High-volume marketing email campaigns, transactional templates, and sender validation.',
    category: 'Communication & AI',
    authType: 'Bearer (SENDGRID_API_KEY)',
    authEnvVar: 'SENDGRID_API_KEY',
    defaultBaseUrl: 'https://api.sendgrid.com/v3',
    tags: ['email', 'templates', 'marketing', 'deliverability'],
  },
  {
    id: 'twilio',
    name: 'Twilio Programmable Messaging & Voice API',
    description: 'Send SMS messages, make voice calls, verify phone numbers, and handle WhatsApp messaging.',
    category: 'Communication & AI',
    authType: 'Basic (TWILIO_ACCOUNT_SID:TWILIO_AUTH_TOKEN)',
    authEnvVar: 'TWILIO_AUTH_TOKEN',
    defaultBaseUrl: 'https://api.twilio.com/2010-04-01',
    tags: ['sms', 'voice', 'whatsapp', '2fa', 'telephony'],
  },
  {
    id: 'postmark',
    name: 'Postmark API',
    description: 'Fast reliable transactional email delivery, message bounce tracking, and inbound processing.',
    category: 'Communication & AI',
    authType: 'Header (X-Postmark-Server-Token)',
    authEnvVar: 'POSTMARK_SERVER_TOKEN',
    defaultBaseUrl: 'https://api.postmarkapp.com',
    tags: ['email', 'bounces', 'transactional', 'inbound'],
  },
  {
    id: 'openai',
    name: 'OpenAI API',
    description: 'Chat completions, embeddings, Assistants, image generation (DALL·E), and audio transcription (Whisper).',
    category: 'Communication & AI',
    authType: 'Bearer (OPENAI_API_KEY)',
    authEnvVar: 'OPENAI_API_KEY',
    defaultBaseUrl: 'https://api.openai.com/v1',
    specUrl: 'https://raw.githubusercontent.com/openai/openai-openapi/master/openapi.yaml',
    tags: ['llm', 'ai', 'gpt4', 'embeddings', 'whisper', 'vision'],
  },
  {
    id: 'anthropic',
    name: 'Anthropic Claude API',
    description: 'Claude 3.5 Sonnet, Haiku, and Opus chat messages, tool calling, and long-context processing.',
    category: 'Communication & AI',
    authType: 'Header (x-api-key)',
    authEnvVar: 'ANTHROPIC_API_KEY',
    defaultBaseUrl: 'https://api.anthropic.com/v1',
    tags: ['llm', 'ai', 'claude', 'reasoning', 'coding'],
  },
  {
    id: 'mistral',
    name: 'Mistral AI API',
    description: 'Mistral Large, Codestral, Pixtral, and embeddings inference endpoints.',
    category: 'Communication & AI',
    authType: 'Bearer (MISTRAL_API_KEY)',
    authEnvVar: 'MISTRAL_API_KEY',
    defaultBaseUrl: 'https://api.mistral.ai/v1',
    tags: ['llm', 'ai', 'mistral', 'codestral', 'open-weights'],
  },
  {
    id: 'togetherai',
    name: 'Together AI Inference API',
    description: 'Fast inference for open-source foundation models (Llama 3, Qwen, DeepSeek, Flux).',
    category: 'Communication & AI',
    authType: 'Bearer (TOGETHER_API_KEY)',
    authEnvVar: 'TOGETHER_API_KEY',
    defaultBaseUrl: 'https://api.together.xyz/v1',
    tags: ['llm', 'llama', 'flux', 'inference', 'open-source'],
  },
  {
    id: 'replicate',
    name: 'Replicate API',
    description: 'Run machine learning models in the cloud via API (image generation, voice synthesis, video).',
    category: 'Communication & AI',
    authType: 'Bearer (REPLICATE_API_TOKEN)',
    authEnvVar: 'REPLICATE_API_TOKEN',
    defaultBaseUrl: 'https://api.replicate.com/v1',
    tags: ['ml', 'diffusion', 'models', 'gpu', 'ai'],
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs Voice AI API',
    description: 'Realistic text-to-speech synthesis, voice cloning, audio isolation, and sound effects.',
    category: 'Communication & AI',
    authType: 'Header (xi-api-key)',
    authEnvVar: 'ELEVENLABS_API_KEY',
    defaultBaseUrl: 'https://api.elevenlabs.io/v1',
    tags: ['tts', 'voice', 'audio', 'speech-synthesis'],
  },
  {
    id: 'deepgram',
    name: 'Deepgram Speech-to-Text API',
    description: 'Real-time and pre-recorded high-accuracy speech transcription and audio intelligence.',
    category: 'Communication & AI',
    authType: 'Bearer (DEEPGRAM_API_KEY)',
    authEnvVar: 'DEEPGRAM_API_KEY',
    defaultBaseUrl: 'https://api.deepgram.com/v1',
    tags: ['stt', 'transcription', 'speech', 'audio'],
  },
];
