import { Preset } from '../types.js';

export const DEVELOPER_TOOLS_PRESETS: Preset[] = [
  {
    id: 'github',
    name: 'GitHub REST API',
    description: 'Manage repositories, pull requests, issues, releases, actions, and branch protections.',
    category: 'Developer Tools',
    authType: 'Bearer (GITHUB_TOKEN)',
    authEnvVar: 'GITHUB_TOKEN',
    defaultBaseUrl: 'https://api.github.com',
    specUrl: 'https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json',
    tags: ['git', 'code', 'issues', 'pr', 'actions', 'ci/cd', 'releases'],
    fieldMasks: [
      { path: '/repos/{owner}/{repo}/issues', fields: ['id', 'number', 'title', 'state', 'user.login', 'created_at', 'html_url'] },
      { path: '/repos/{owner}/{repo}/pulls', fields: ['id', 'number', 'title', 'state', 'user.login', 'head.ref', 'base.ref', 'html_url'] },
    ],
    macros: [
      {
        name: 'createIssueAndComment',
        description: 'Creates a new issue in a repository and immediately adds a follow-up comment',
        parameters: {
          type: 'object',
          properties: {
            owner: { type: 'string' },
            repo: { type: 'string' },
            title: { type: 'string' },
            body: { type: 'string' },
            comment: { type: 'string' },
          },
          required: ['owner', 'repo', 'title'],
        },
        steps: [
          { id: 'createIssue', action: 'POST /repos/{{owner}}/{{repo}}/issues', body: { title: '{{title}}', body: '{{body}}' }, export: { issueNumber: 'number' } },
          { id: 'addComment', action: 'POST /repos/{{owner}}/{{repo}}/issues/{{issueNumber}}/comments', body: { body: '{{comment}}' } },
        ],
      },
    ],
  },
  {
    id: 'gitlab',
    name: 'GitLab REST API',
    description: 'GitLab project management, merge requests, CI/CD pipelines, and repository administration.',
    category: 'Developer Tools',
    authType: 'Header (PRIVATE-TOKEN)',
    authEnvVar: 'GITLAB_TOKEN',
    defaultBaseUrl: 'https://gitlab.com/api/v4',
    tags: ['git', 'merge-requests', 'pipelines', 'devops'],
  },
  {
    id: 'jira',
    name: 'Jira Software Cloud API',
    description: 'Atlassian Jira project tracking, issues, sprints, boards, and workflows.',
    category: 'Developer Tools',
    authType: 'Basic (JIRA_EMAIL:JIRA_API_TOKEN)',
    authEnvVar: 'JIRA_API_TOKEN',
    defaultBaseUrl: 'https://your-domain.atlassian.net/rest/api/3',
    tags: ['agile', 'sprints', 'tickets', 'scrum', 'kanban'],
  },
  {
    id: 'linear',
    name: 'Linear API',
    description: 'Fast project tracking, issues, milestones, teams, and cycles.',
    category: 'Developer Tools',
    authType: 'Bearer (LINEAR_API_KEY)',
    authEnvVar: 'LINEAR_API_KEY',
    defaultBaseUrl: 'https://api.linear.app',
    tags: ['issues', 'roadmap', 'cycles', 'product'],
  },
  {
    id: 'sentry',
    name: 'Sentry API',
    description: 'Application error monitoring, performance telemetry, release tracking, and alerting.',
    category: 'Developer Tools',
    authType: 'Bearer (SENTRY_AUTH_TOKEN)',
    authEnvVar: 'SENTRY_AUTH_TOKEN',
    defaultBaseUrl: 'https://sentry.io/api/0',
    tags: ['errors', 'crash-reporting', 'performance', 'alerts'],
  },
  {
    id: 'datadog',
    name: 'Datadog API',
    description: 'Infrastructure metrics, distributed traces, logs, synthetic tests, and dashboards.',
    category: 'Developer Tools',
    authType: 'Header (DD-API-KEY / DD-APPLICATION-KEY)',
    authEnvVar: 'DATADOG_API_KEY',
    defaultBaseUrl: 'https://api.datadoghq.com/api/v2',
    tags: ['metrics', 'traces', 'logs', 'observability'],
  },
  {
    id: 'postman',
    name: 'Postman API',
    description: 'Manage Postman workspaces, API collections, environments, and mock servers.',
    category: 'Developer Tools',
    authType: 'Header (X-Api-Key)',
    authEnvVar: 'POSTMAN_API_KEY',
    defaultBaseUrl: 'https://api.getpostman.com',
    tags: ['api-testing', 'collections', 'documentation', 'mocks'],
  },
  {
    id: 'vercel',
    name: 'Vercel API',
    description: 'Deploy frontend projects, manage custom domains, edge middleware, and serverless functions.',
    category: 'Developer Tools',
    authType: 'Bearer (VERCEL_TOKEN)',
    authEnvVar: 'VERCEL_TOKEN',
    defaultBaseUrl: 'https://api.vercel.com',
    specUrl: 'https://raw.githubusercontent.com/vercel/openapi/main/openapi.json',
    tags: ['hosting', 'deployments', 'domains', 'serverless', 'nextjs'],
  },
  {
    id: 'docker',
    name: 'Docker Hub API',
    description: 'Query container images, repositories, tags, and automated build webhooks.',
    category: 'Developer Tools',
    authType: 'Bearer (DOCKER_ACCESS_TOKEN)',
    authEnvVar: 'DOCKER_ACCESS_TOKEN',
    defaultBaseUrl: 'https://hub.docker.com/v2',
    tags: ['containers', 'images', 'registries', 'devops'],
  },
  {
    id: 'npm',
    name: 'NPM Registry API',
    description: 'Query packages, version metadata, maintainers, dependencies, and download statistics.',
    category: 'Developer Tools',
    authType: 'Bearer (NPM_TOKEN)',
    authEnvVar: 'NPM_TOKEN',
    defaultBaseUrl: 'https://registry.npmjs.org',
    tags: ['packages', 'javascript', 'typescript', 'modules'],
  },
  {
    id: 'pagerduty',
    name: 'PagerDuty API',
    description: 'Incident response, on-call scheduling, escalations, and service health alerting.',
    category: 'Developer Tools',
    authType: 'Header (Authorization: Token token=...)',
    authEnvVar: 'PAGERDUTY_TOKEN',
    defaultBaseUrl: 'https://api.pagerduty.com',
    tags: ['incidents', 'on-call', 'alerts', 'devops'],
  },
  {
    id: 'grafana',
    name: 'Grafana HTTP API',
    description: 'Manage dashboards, datasources, alert rules, user permissions, and telemetry visualization.',
    category: 'Developer Tools',
    authType: 'Bearer (GRAFANA_SERVICE_ACCOUNT_TOKEN)',
    authEnvVar: 'GRAFANA_TOKEN',
    defaultBaseUrl: 'https://grafana.example.com/api',
    tags: ['dashboards', 'monitoring', 'visualization', 'datasources'],
  },
  {
    id: 'opsgenie',
    name: 'OpsGenie API',
    description: 'Alert and incident management, escalation policies, and team rotations.',
    category: 'Developer Tools',
    authType: 'Header (GenieKey ...)',
    authEnvVar: 'OPSGENIE_KEY',
    defaultBaseUrl: 'https://api.opsgenie.com/v2',
    tags: ['incidents', 'escalation', 'alerts', 'oncall'],
  },
];
