import { Preset } from '../types.js';

export const MEDIA_SOCIAL_PRESETS: Preset[] = [
  {
    id: 'twitter',
    name: 'X / Twitter API v2',
    description: 'Post tweets, search recent posts, query user timelines, and manage follower relationships.',
    category: 'Social & Media',
    authType: 'Bearer (TWITTER_BEARER_TOKEN)',
    authEnvVar: 'TWITTER_BEARER_TOKEN',
    defaultBaseUrl: 'https://api.twitter.com/2',
    tags: ['social', 'tweets', 'posts', 'timeline', 'media'],
  },
  {
    id: 'youtube',
    name: 'YouTube Data API v3',
    description: 'Search video library, manage playlists, upload video assets, and retrieve channel analytics.',
    category: 'Social & Media',
    authType: 'Bearer / Key (YOUTUBE_API_KEY)',
    authEnvVar: 'YOUTUBE_API_KEY',
    defaultBaseUrl: 'https://www.googleapis.com/youtube/v3',
    tags: ['video', 'streaming', 'playlists', 'channels', 'media'],
  },
  {
    id: 'spotify',
    name: 'Spotify Web API',
    description: 'Query artist catalogs, search music tracks/albums, control user playback, and create playlists.',
    category: 'Social & Media',
    authType: 'Bearer (SPOTIFY_ACCESS_TOKEN)',
    authEnvVar: 'SPOTIFY_ACCESS_TOKEN',
    defaultBaseUrl: 'https://api.spotify.com/v1',
    tags: ['music', 'audio', 'playlists', 'tracks', 'playback'],
  },
  {
    id: 'cloudinary',
    name: 'Cloudinary Admin & Upload API',
    description: 'Cloud media storage, AI image transformations, video encoding, and CDN optimization.',
    category: 'Social & Media',
    authType: 'Basic (CLOUDINARY_API_KEY:CLOUDINARY_API_SECRET)',
    authEnvVar: 'CLOUDINARY_API_KEY',
    defaultBaseUrl: 'https://api.cloudinary.com/v1_1/{cloud_name}',
    tags: ['images', 'video', 'cdn', 'transformations', 'media-storage'],
  },
  {
    id: 'petstore',
    name: 'Swagger Petstore',
    description: 'Standard OpenAPI reference API for testing, benchmarking, and demoing MCP servers.',
    category: 'Demo & Testing',
    authType: 'apiKey / None',
    defaultBaseUrl: 'https://petstore.swagger.io/v2',
    specUrl: 'https://petstore.swagger.io/v2/swagger.json',
    tags: ['demo', 'testing', 'pets', 'store', 'reference'],
  },
];
