import { Preset } from '../types.js';
import { buildOpenAPISpec } from '../builder.js';

export const PAYMENTS_COMMERCE_PRESETS: Preset[] = [
  {
    id: 'stripe',
    name: 'Stripe API',
    description: 'Process payments, create customer subscriptions, issue refunds, manage invoices, and dispute balances.',
    category: 'Payments & Commerce',
    authType: 'Bearer (STRIPE_SECRET_KEY)',
    authEnvVar: 'STRIPE_SECRET_KEY',
    defaultBaseUrl: 'https://api.stripe.com/v1',
    specUrl: 'https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json',
    tags: ['payments', 'billing', 'invoices', 'cards', 'subscriptions', 'refunds'],
    fieldMasks: [
      { path: '/v1/charges', fields: ['id', 'amount', 'currency', 'customer', 'status', 'refunded'] },
      { path: '/v1/refunds', fields: ['id', 'amount', 'currency', 'charge', 'status', 'reason'] },
      { path: '/v1/customers', fields: ['id', 'email', 'name', 'balance', 'created'] },
    ],
    macros: [
      {
        name: 'refundCustomerCharge',
        description: 'Looks up the latest charge for a customer and issues a refund',
        parameters: {
          type: 'object',
          properties: {
            customer: { type: 'string', description: 'Stripe customer ID' },
            reason: { type: 'string', description: 'Reason for refund' },
          },
          required: ['customer'],
        },
        steps: [
          { id: 'listCharges', action: 'GET /v1/charges?customer={{customer}}&limit=1', export: { chargeId: 'data[0].id' } },
          { id: 'createRefund', action: 'POST /v1/refunds', body: { charge: '{{chargeId}}', reason: '{{reason}}' } },
        ],
      },
    ],
    bundledSpec: buildOpenAPISpec({
      title: 'Stripe API',
      baseUrl: 'https://api.stripe.com/v1',
      description: 'Stripe Payments and Subscriptions API',
      securityScheme: { name: 'bearerAuth', type: 'http', scheme: 'bearer' },
      endpoints: [
        { path: '/v1/charges', method: 'get', operationId: 'listCharges', summary: 'List charges', parameters: [{ name: 'customer', in: 'query', schema: { type: 'string' } }, { name: 'limit', in: 'query', schema: { type: 'integer' } }] },
        { path: '/v1/charges', method: 'post', operationId: 'createCharge', summary: 'Create charge', requestBody: { properties: { amount: { type: 'integer' }, currency: { type: 'string' }, source: { type: 'string' } } } },
        { path: '/v1/refunds', method: 'get', operationId: 'listRefunds', summary: 'List refunds' },
        { path: '/v1/refunds', method: 'post', operationId: 'createRefund', summary: 'Create refund', requestBody: { properties: { charge: { type: 'string' }, amount: { type: 'integer' }, reason: { type: 'string' } } } },
        { path: '/v1/customers', method: 'get', operationId: 'listCustomers', summary: 'List customers', parameters: [{ name: 'email', in: 'query', schema: { type: 'string' } }] },
        { path: '/v1/customers', method: 'post', operationId: 'createCustomer', summary: 'Create customer', requestBody: { properties: { email: { type: 'string' }, name: { type: 'string' } } } },
      ],
    }),
  },
  {
    id: 'shopify',
    name: 'Shopify Admin API',
    description: 'Manage store products, orders, inventory levels, collections, and customer accounts.',
    category: 'Payments & Commerce',
    authType: 'Header (X-Shopify-Access-Token)',
    authEnvVar: 'SHOPIFY_ACCESS_TOKEN',
    defaultBaseUrl: 'https://{shop}.myshopify.com/admin/api/2024-01',
    tags: ['ecommerce', 'products', 'orders', 'inventory', 'storefront'],
    fieldMasks: [
      { path: '/products.json', fields: ['products.id', 'products.title', 'products.vendor', 'products.status', 'products.variants'] },
      { path: '/orders.json', fields: ['orders.id', 'orders.name', 'orders.total_price', 'orders.financial_status', 'orders.created_at'] },
    ],
    bundledSpec: buildOpenAPISpec({
      title: 'Shopify Admin API',
      baseUrl: 'https://example-shop.myshopify.com/admin/api/2024-01',
      description: 'Shopify Storefront & Admin API',
      securityScheme: { name: 'shopifyAuth', type: 'apiKey', in: 'header', headerName: 'X-Shopify-Access-Token' },
      endpoints: [
        { path: '/products.json', method: 'get', operationId: 'listProducts', summary: 'List store products' },
        { path: '/products/{id}.json', method: 'get', operationId: 'getProduct', summary: 'Get product details', parameters: [{ name: 'id', in: 'path', schema: { type: 'string' } }] },
        { path: '/orders.json', method: 'get', operationId: 'listOrders', summary: 'List store orders' },
        { path: '/customers.json', method: 'get', operationId: 'listCustomers', summary: 'List store customers' },
      ],
    }),
  },
  {
    id: 'paypal',
    name: 'PayPal REST API',
    description: 'Create checkout orders, manage subscriptions, process payouts, and handle buyer disputes.',
    category: 'Payments & Commerce',
    authType: 'Bearer (PAYPAL_ACCESS_TOKEN)',
    authEnvVar: 'PAYPAL_ACCESS_TOKEN',
    defaultBaseUrl: 'https://api-m.paypal.com',
    tags: ['payments', 'checkout', 'payouts', 'orders'],
    fieldMasks: [
      { path: '/v2/checkout/orders/{id}', fields: ['id', 'status', 'intent', 'purchase_units.amount'] },
    ],
    bundledSpec: buildOpenAPISpec({
      title: 'PayPal REST API',
      baseUrl: 'https://api-m.paypal.com',
      description: 'PayPal Checkout & Payments API',
      securityScheme: { name: 'bearerAuth', type: 'http', scheme: 'bearer' },
      endpoints: [
        { path: '/v2/checkout/orders', method: 'post', operationId: 'createOrder', summary: 'Create checkout order', requestBody: { properties: { intent: { type: 'string' }, purchase_units: { type: 'array' } } } },
        { path: '/v2/checkout/orders/{id}', method: 'get', operationId: 'getOrder', summary: 'Get order details', parameters: [{ name: 'id', in: 'path', schema: { type: 'string' } }] },
        { path: '/v2/checkout/orders/{id}/capture', method: 'post', operationId: 'captureOrder', summary: 'Capture order payment', parameters: [{ name: 'id', in: 'path', schema: { type: 'string' } }] },
      ],
    }),
  },
  {
    id: 'square',
    name: 'Square API',
    description: 'Point-of-sale terminal transactions, catalog items, customers, and merchant inventory.',
    category: 'Payments & Commerce',
    authType: 'Bearer (SQUARE_ACCESS_TOKEN)',
    authEnvVar: 'SQUARE_ACCESS_TOKEN',
    defaultBaseUrl: 'https://connect.squareup.com/v2',
    tags: ['pos', 'merchant', 'payments', 'catalog', 'inventory'],
    bundledSpec: buildOpenAPISpec({
      title: 'Square API',
      baseUrl: 'https://connect.squareup.com/v2',
      description: 'Square Merchant & Payments API',
      securityScheme: { name: 'bearerAuth', type: 'http', scheme: 'bearer' },
      endpoints: [
        { path: '/locations', method: 'get', operationId: 'listLocations', summary: 'List business locations' },
        { path: '/payments', method: 'get', operationId: 'listPayments', summary: 'List processed payments' },
        { path: '/catalog/list', method: 'get', operationId: 'listCatalog', summary: 'List catalog items' },
      ],
    }),
  },
  {
    id: 'chargebee',
    name: 'Chargebee API',
    description: 'SaaS subscription billing, revenue recognition, metered usage, and invoice automation.',
    category: 'Payments & Commerce',
    authType: 'Basic (CHARGEBEE_API_KEY:)',
    authEnvVar: 'CHARGEBEE_API_KEY',
    defaultBaseUrl: 'https://{site}.chargebee.com/api/v2',
    tags: ['subscriptions', 'saas', 'billing', 'invoices'],
    bundledSpec: buildOpenAPISpec({
      title: 'Chargebee API',
      baseUrl: 'https://example-site.chargebee.com/api/v2',
      description: 'Chargebee Subscription Management API',
      securityScheme: { name: 'basicAuth', type: 'http', scheme: 'basic' },
      endpoints: [
        { path: '/subscriptions', method: 'get', operationId: 'listSubscriptions', summary: 'List subscriptions' },
        { path: '/invoices', method: 'get', operationId: 'listInvoices', summary: 'List customer invoices' },
        { path: '/customers', method: 'get', operationId: 'listCustomers', summary: 'List billing customers' },
      ],
    }),
  },
  {
    id: 'paddle',
    name: 'Paddle Billing API',
    description: 'Merchant of Record billing, global sales tax compliance, checkout, and subscriptions.',
    category: 'Payments & Commerce',
    authType: 'Bearer (PADDLE_API_KEY)',
    authEnvVar: 'PADDLE_API_KEY',
    defaultBaseUrl: 'https://api.paddle.com',
    tags: ['mor', 'billing', 'taxes', 'checkout', 'saas'],
    bundledSpec: buildOpenAPISpec({
      title: 'Paddle Billing API',
      baseUrl: 'https://api.paddle.com',
      description: 'Paddle Merchant of Record API',
      securityScheme: { name: 'bearerAuth', type: 'http', scheme: 'bearer' },
      endpoints: [
        { path: '/products', method: 'get', operationId: 'listProducts', summary: 'List catalog products' },
        { path: '/prices', method: 'get', operationId: 'listPrices', summary: 'List product prices' },
        { path: '/subscriptions', method: 'get', operationId: 'listSubscriptions', summary: 'List active subscriptions' },
      ],
    }),
  },
  {
    id: 'plaid',
    name: 'Plaid API',
    description: 'Connect user bank accounts, verify balances, retrieve transaction history, and auth ACH transfers.',
    category: 'Payments & Commerce',
    authType: 'Header (PLAID-CLIENT-ID / PLAID-SECRET)',
    authEnvVar: 'PLAID_SECRET',
    defaultBaseUrl: 'https://production.plaid.com',
    tags: ['banking', 'ach', 'transactions', 'fintech', 'balances'],
    fieldMasks: [
      { path: '/accounts/balance/get', fields: ['accounts.account_id', 'accounts.name', 'accounts.balances.current', 'accounts.balances.iso_currency_code'] },
    ],
    bundledSpec: buildOpenAPISpec({
      title: 'Plaid API',
      baseUrl: 'https://production.plaid.com',
      description: 'Plaid Open Banking API',
      securityScheme: { name: 'plaidAuth', type: 'apiKey', in: 'header', headerName: 'PLAID-SECRET' },
      endpoints: [
        { path: '/accounts/balance/get', method: 'post', operationId: 'getBalances', summary: 'Retrieve account balances', requestBody: { properties: { access_token: { type: 'string' } } } },
        { path: '/transactions/sync', method: 'post', operationId: 'syncTransactions', summary: 'Sync bank transactions', requestBody: { properties: { access_token: { type: 'string' } } } },
      ],
    }),
  },
  {
    id: 'brex',
    name: 'Brex API',
    description: 'Corporate card management, expense budgets, team transaction approvals, and vendor payments.',
    category: 'Payments & Commerce',
    authType: 'Bearer (BREX_API_KEY)',
    authEnvVar: 'BREX_API_KEY',
    defaultBaseUrl: 'https://platform.brexapis.com/v2',
    tags: ['cards', 'expenses', 'banking', 'fintech'],
    bundledSpec: buildOpenAPISpec({
      title: 'Brex API',
      baseUrl: 'https://platform.brexapis.com/v2',
      description: 'Brex Corporate Spend Management API',
      securityScheme: { name: 'bearerAuth', type: 'http', scheme: 'bearer' },
      endpoints: [
        { path: '/accounts', method: 'get', operationId: 'listAccounts', summary: 'List cash accounts' },
        { path: '/transactions/card/primary', method: 'get', operationId: 'listCardTransactions', summary: 'List primary card transactions' },
        { path: '/users/me', method: 'get', operationId: 'getMe', summary: 'Get current user profile' },
      ],
    }),
  },
  {
    id: 'ramp',
    name: 'Ramp Developer API',
    description: 'Spend management, employee corporate cards, expense policies, and accounting synchronization.',
    category: 'Payments & Commerce',
    authType: 'Bearer (RAMP_CLIENT_SECRET)',
    authEnvVar: 'RAMP_SECRET',
    defaultBaseUrl: 'https://api.ramp.com/developer/v1',
    tags: ['spend-management', 'cards', 'expenses', 'accounting'],
    bundledSpec: buildOpenAPISpec({
      title: 'Ramp Developer API',
      baseUrl: 'https://api.ramp.com/developer/v1',
      description: 'Ramp Corporate Card & Spend API',
      securityScheme: { name: 'bearerAuth', type: 'http', scheme: 'bearer' },
      endpoints: [
        { path: '/users', method: 'get', operationId: 'listUsers', summary: 'List company users' },
        { path: '/cards', method: 'get', operationId: 'listCards', summary: 'List issued corporate cards' },
        { path: '/transactions', method: 'get', operationId: 'listTransactions', summary: 'List spend transactions' },
      ],
    }),
  },
];
