import { Preset } from '../types.js';

export const PAYMENTS_COMMERCE_PRESETS: Preset[] = [
  {
    id: 'stripe',
    name: 'Stripe API',
    description: 'Process payments, create customer subscriptions, issue refunds, manage invoices, and dispute balances.',
    category: 'Payments & Commerce',
    authType: 'Bearer (STRIPE_SECRET_KEY)',
    authEnvVar: 'STRIPE_SECRET_KEY',
    defaultBaseUrl: 'https://api.stripe.com/v1',
    specUrl: 'https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json',
    tags: ['payments', 'billing', 'invoices', 'cards', 'subscriptions', 'refunds'],
    fieldMasks: [
      { path: '/v1/charges', fields: ['id', 'amount', 'currency', 'customer', 'status', 'refunded'] },
      { path: '/v1/refunds', fields: ['id', 'amount', 'currency', 'charge', 'status', 'reason'] },
      { path: '/v1/customers', fields: ['id', 'email', 'name', 'balance', 'created'] },
    ],
    macros: [
      {
        name: 'refundCustomerCharge',
        description: 'Looks up the latest charge for a customer and issues a refund',
        parameters: {
          type: 'object',
          properties: {
            customer: { type: 'string', description: 'Stripe customer ID' },
            reason: { type: 'string', description: 'Reason for refund' },
          },
          required: ['customer'],
        },
        steps: [
          { id: 'listCharges', action: 'GET /v1/charges?customer={{customer}}&limit=1', export: { chargeId: 'data[0].id' } },
          { id: 'createRefund', action: 'POST /v1/refunds', body: { charge: '{{chargeId}}', reason: '{{reason}}' } },
        ],
      },
    ],
  },
  {
    id: 'shopify',
    name: 'Shopify Admin API',
    description: 'Manage store products, orders, inventory levels, collections, and customer accounts.',
    category: 'Payments & Commerce',
    authType: 'Header (X-Shopify-Access-Token)',
    authEnvVar: 'SHOPIFY_ACCESS_TOKEN',
    defaultBaseUrl: 'https://{shop}.myshopify.com/admin/api/2024-01',
    tags: ['ecommerce', 'products', 'orders', 'inventory', 'storefront'],
  },
  {
    id: 'paypal',
    name: 'PayPal REST API',
    description: 'Create checkout orders, manage subscriptions, process payouts, and handle buyer disputes.',
    category: 'Payments & Commerce',
    authType: 'Bearer (PAYPAL_ACCESS_TOKEN)',
    authEnvVar: 'PAYPAL_ACCESS_TOKEN',
    defaultBaseUrl: 'https://api-m.paypal.com',
    tags: ['payments', 'checkout', 'payouts', 'orders'],
  },
  {
    id: 'square',
    name: 'Square API',
    description: 'Point-of-sale terminal transactions, catalog items, customers, and merchant inventory.',
    category: 'Payments & Commerce',
    authType: 'Bearer (SQUARE_ACCESS_TOKEN)',
    authEnvVar: 'SQUARE_ACCESS_TOKEN',
    defaultBaseUrl: 'https://connect.squareup.com/v2',
    tags: ['pos', 'merchant', 'payments', 'catalog', 'inventory'],
  },
  {
    id: 'chargebee',
    name: 'Chargebee API',
    description: 'SaaS subscription billing, revenue recognition, metered usage, and invoice automation.',
    category: 'Payments & Commerce',
    authType: 'Basic (CHARGEBEE_API_KEY:)',
    authEnvVar: 'CHARGEBEE_API_KEY',
    defaultBaseUrl: 'https://{site}.chargebee.com/api/v2',
    tags: ['subscriptions', 'saas', 'billing', 'invoices'],
  },
  {
    id: 'paddle',
    name: 'Paddle Billing API',
    description: 'Merchant of Record billing, global sales tax compliance, checkout, and subscriptions.',
    category: 'Payments & Commerce',
    authType: 'Bearer (PADDLE_API_KEY)',
    authEnvVar: 'PADDLE_API_KEY',
    defaultBaseUrl: 'https://api.paddle.com',
    tags: ['mor', 'billing', 'taxes', 'checkout', 'saas'],
  },
  {
    id: 'plaid',
    name: 'Plaid API',
    description: 'Connect user bank accounts, verify balances, retrieve transaction history, and auth ACH transfers.',
    category: 'Payments & Commerce',
    authType: 'Header (PLAID-CLIENT-ID / PLAID-SECRET)',
    authEnvVar: 'PLAID_SECRET',
    defaultBaseUrl: 'https://production.plaid.com',
    tags: ['banking', 'ach', 'transactions', 'fintech', 'balances'],
  },
  {
    id: 'brex',
    name: 'Brex API',
    description: 'Corporate card management, expense budgets, team transaction approvals, and vendor payments.',
    category: 'Payments & Commerce',
    authType: 'Bearer (BREX_API_KEY)',
    authEnvVar: 'BREX_API_KEY',
    defaultBaseUrl: 'https://platform.brexapis.com/v2',
    tags: ['cards', 'expenses', 'banking', 'fintech'],
  },
  {
    id: 'ramp',
    name: 'Ramp Developer API',
    description: 'Spend management, employee corporate cards, expense policies, and accounting synchronization.',
    category: 'Payments & Commerce',
    authType: 'Bearer (RAMP_CLIENT_SECRET)',
    authEnvVar: 'RAMP_SECRET',
    defaultBaseUrl: 'https://api.ramp.com/developer/v1',
    tags: ['spend-management', 'cards', 'expenses', 'accounting'],
  },
];
