import { Preset } from '../types.js';
import { buildOpenAPISpec } from '../builder.js';

export const PRODUCTIVITY_SUPPORT_PRESETS: Preset[] = [
  {
    id: 'notion',
    name: 'Notion API',
    description: 'Query and mutate Notion workspaces, databases, pages, nested blocks, and user comments.',
    category: 'Productivity & Support',
    authType: 'Bearer (NOTION_API_KEY)',
    authEnvVar: 'NOTION_API_KEY',
    defaultBaseUrl: 'https://api.notion.com/v1',
    tags: ['docs', 'wiki', 'databases', 'pages', 'notes'],
    fieldMasks: [
      { path: '/databases/{database_id}/query', fields: ['results.id', 'results.properties', 'results.url'] },
    ],
    macros: [
      {
        name: 'createDatabasePage',
        description: 'Creates a page inside a Notion database with properties',
        parameters: {
          type: 'object',
          properties: {
            database_id: { type: 'string' },
            title: { type: 'string' },
          },
          required: ['database_id', 'title'],
        },
        steps: [
          { id: 'createPage', action: 'POST /pages', body: { parent: { database_id: '{{database_id}}' }, properties: { Name: { title: [{ text: { content: '{{title}}' } }] } } } },
        ],
      },
    ],
    bundledSpec: buildOpenAPISpec({
      title: 'Notion API',
      baseUrl: 'https://api.notion.com/v1',
      description: 'Notion Workspace & Database API',
      securityScheme: { name: 'bearerAuth', type: 'http', scheme: 'bearer' },
      endpoints: [
        { path: '/users/me', method: 'get', operationId: 'getMe', summary: 'Get current bot user' },
        { path: '/search', method: 'post', operationId: 'searchObjects', summary: 'Search pages and databases', requestBody: { properties: { query: { type: 'string' } } } },
        { path: '/databases/{database_id}', method: 'get', operationId: 'getDatabase', summary: 'Get database schema', parameters: [{ name: 'database_id', in: 'path', schema: { type: 'string' } }] },
        { path: '/databases/{database_id}/query', method: 'post', operationId: 'queryDatabase', summary: 'Query database rows', parameters: [{ name: 'database_id', in: 'path', schema: { type: 'string' } }], requestBody: { properties: { filter: { type: 'object' } } } },
        { path: '/pages', method: 'post', operationId: 'createPage', summary: 'Create new page', requestBody: { properties: { parent: { type: 'object' }, properties: { type: 'object' } } } },
      ],
    }),
  },
  {
    id: 'slack',
    name: 'Slack Web API',
    description: 'Post messages to channels, manage user groups, trigger modals, and upload file attachments.',
    category: 'Productivity & Support',
    authType: 'Bearer (SLACK_BOT_TOKEN)',
    authEnvVar: 'SLACK_BOT_TOKEN',
    defaultBaseUrl: 'https://slack.com/api',
    specUrl: 'https://raw.githubusercontent.com/slackapi/slack-api-specs/master/web-api/slack_web_openapi_v2.json',
    tags: ['chat', 'messaging', 'bots', 'channels', 'collaboration'],
    macros: [
      {
        name: 'postToChannel',
        description: 'Sends a formatted message to a specific Slack channel',
        parameters: {
          type: 'object',
          properties: {
            channel: { type: 'string', description: 'Channel ID or name' },
            text: { type: 'string', description: 'Message body' },
          },
          required: ['channel', 'text'],
        },
        steps: [
          { id: 'postMsg', action: 'POST /chat.postMessage', body: { channel: '{{channel}}', text: '{{text}}' } },
        ],
      },
    ],
    bundledSpec: buildOpenAPISpec({
      title: 'Slack Web API',
      baseUrl: 'https://slack.com/api',
      description: 'Slack Team Messaging API',
      securityScheme: { name: 'bearerAuth', type: 'http', scheme: 'bearer' },
      endpoints: [
        { path: '/auth.test', method: 'post', operationId: 'testAuth', summary: 'Check Slack bot credentials' },
        { path: '/conversations.list', method: 'get', operationId: 'listConversations', summary: 'List public/private channels' },
        { path: '/chat.postMessage', method: 'post', operationId: 'postMessage', summary: 'Send message to channel', requestBody: { properties: { channel: { type: 'string' }, text: { type: 'string' } } } },
        { path: '/users.list', method: 'get', operationId: 'listUsers', summary: 'List workspace users' },
      ],
    }),
  },
  {
    id: 'discord',
    name: 'Discord API',
    description: 'Discord bot automation, server administration, voice channels, and rich embedded messages.',
    category: 'Productivity & Support',
    authType: 'Header (Bot ...)',
    authEnvVar: 'DISCORD_BOT_TOKEN',
    defaultBaseUrl: 'https://discord.com/api/v10',
    tags: ['chat', 'gaming', 'community', 'bots', 'guilds'],
    bundledSpec: buildOpenAPISpec({
      title: 'Discord API',
      baseUrl: 'https://discord.com/api/v10',
      description: 'Discord Bot API',
      securityScheme: { name: 'botAuth', type: 'apiKey', in: 'header', headerName: 'Authorization' },
      endpoints: [
        { path: '/users/@me', method: 'get', operationId: 'getCurrentBotUser', summary: 'Get current bot details' },
        { path: '/channels/{channel_id}/messages', method: 'post', operationId: 'createChannelMessage', summary: 'Send message to Discord channel', parameters: [{ name: 'channel_id', in: 'path', schema: { type: 'string' } }], requestBody: { properties: { content: { type: 'string' } } } },
        { path: '/guilds/{guild_id}', method: 'get', operationId: 'getGuild', summary: 'Get guild details', parameters: [{ name: 'guild_id', in: 'path', schema: { type: 'string' } }] },
      ],
    }),
  },
  {
    id: 'airtable',
    name: 'Airtable REST API',
    description: 'Relational database sheets, record filtering, formula fields, and view automations.',
    category: 'Productivity & Support',
    authType: 'Bearer (AIRTABLE_PERSONAL_ACCESS_TOKEN)',
    authEnvVar: 'AIRTABLE_API_KEY',
    defaultBaseUrl: 'https://api.airtable.com/v0',
    tags: ['spreadsheet', 'database', 'nocode', 'tables', 'records'],
    fieldMasks: [
      { path: '/{baseId}/{tableIdOrName}', fields: ['records.id', 'records.fields', 'records.createdTime'] },
    ],
    bundledSpec: buildOpenAPISpec({
      title: 'Airtable REST API',
      baseUrl: 'https://api.airtable.com/v0',
      description: 'Airtable Database API',
      securityScheme: { name: 'bearerAuth', type: 'http', scheme: 'bearer' },
      endpoints: [
        { path: '/{baseId}/{tableIdOrName}', method: 'get', operationId: 'listRecords', summary: 'List table records', parameters: [{ name: 'baseId', in: 'path', schema: { type: 'string' } }, { name: 'tableIdOrName', in: 'path', schema: { type: 'string' } }] },
        { path: '/{baseId}/{tableIdOrName}', method: 'post', operationId: 'createRecords', summary: 'Create table records', parameters: [{ name: 'baseId', in: 'path', schema: { type: 'string' } }, { name: 'tableIdOrName', in: 'path', schema: { type: 'string' } }], requestBody: { properties: { records: { type: 'array' } } } },
      ],
    }),
  },
  {
    id: 'asana',
    name: 'Asana API',
    description: 'Team tasks, milestones, portfolios, subtasks, custom fields, and project timelines.',
    category: 'Productivity & Support',
    authType: 'Bearer (ASANA_ACCESS_TOKEN)',
    authEnvVar: 'ASANA_ACCESS_TOKEN',
    defaultBaseUrl: 'https://app.asana.com/api/1.0',
    tags: ['tasks', 'projects', 'collaboration', 'teams'],
    bundledSpec: buildOpenAPISpec({
      title: 'Asana API',
      baseUrl: 'https://app.asana.com/api/1.0',
      description: 'Asana Task & Project Management API',
      securityScheme: { name: 'bearerAuth', type: 'http', scheme: 'bearer' },
      endpoints: [
        { path: '/users/me', method: 'get', operationId: 'getMe', summary: 'Get current user profile' },
        { path: '/projects', method: 'get', operationId: 'listProjects', summary: 'List projects' },
        { path: '/tasks', method: 'get', operationId: 'listTasks', summary: 'List tasks', parameters: [{ name: 'project', in: 'query', schema: { type: 'string' } }] },
        { path: '/tasks', method: 'post', operationId: 'createTask', summary: 'Create task', requestBody: { properties: { data: { type: 'object' } } } },
      ],
    }),
  },
  {
    id: 'monday',
    name: 'Monday.com GraphQL/REST API',
    description: 'Work OS boards, column updates, item tracking, and workflow automation.',
    category: 'Productivity & Support',
    authType: 'Bearer (MONDAY_API_TOKEN)',
    authEnvVar: 'MONDAY_API_TOKEN',
    defaultBaseUrl: 'https://api.monday.com/v2',
    tags: ['work-management', 'boards', 'items', 'teams'],
    bundledSpec: buildOpenAPISpec({
      title: 'Monday.com API',
      baseUrl: 'https://api.monday.com/v2',
      description: 'Monday.com Work OS API',
      securityScheme: { name: 'bearerAuth', type: 'http', scheme: 'bearer' },
      endpoints: [
        { path: '/boards', method: 'get', operationId: 'listBoards', summary: 'List boards' },
        { path: '/items', method: 'get', operationId: 'listItems', summary: 'List items' },
      ],
    }),
  },
  {
    id: 'clickup',
    name: 'ClickUp API',
    description: 'Spaces, folders, lists, task statuses, time tracking, and custom field management.',
    category: 'Productivity & Support',
    authType: 'Bearer (CLICKUP_API_TOKEN)',
    authEnvVar: 'CLICKUP_API_TOKEN',
    defaultBaseUrl: 'https://api.clickup.com/api/v2',
    tags: ['tasks', 'productivity', 'project-management', 'time-tracking'],
    bundledSpec: buildOpenAPISpec({
      title: 'ClickUp API',
      baseUrl: 'https://api.clickup.com/api/v2',
      description: 'ClickUp Work Management API',
      securityScheme: { name: 'bearerAuth', type: 'http', scheme: 'bearer' },
      endpoints: [
        { path: '/user', method: 'get', operationId: 'getUser', summary: 'Get current user profile' },
        { path: '/team', method: 'get', operationId: 'getTeams', summary: 'Get workspaces' },
        { path: '/team/{team_id}/space', method: 'get', operationId: 'getSpaces', summary: 'List spaces in workspace', parameters: [{ name: 'team_id', in: 'path', schema: { type: 'string' } }] },
      ],
    }),
  },
  {
    id: 'trello',
    name: 'Trello REST API',
    description: 'Kanban boards, lists, cards, checklist items, and power-up webhooks.',
    category: 'Productivity & Support',
    authType: 'Query (key=...&token=...)',
    authEnvVar: 'TRELLO_TOKEN',
    defaultBaseUrl: 'https://api.trello.com/1',
    tags: ['kanban', 'cards', 'boards', 'collaboration'],
    bundledSpec: buildOpenAPISpec({
      title: 'Trello REST API',
      baseUrl: 'https://api.trello.com/1',
      description: 'Trello Kanban API',
      endpoints: [
        { path: '/members/me', method: 'get', operationId: 'getMe', summary: 'Get member details' },
        { path: '/members/me/boards', method: 'get', operationId: 'listBoards', summary: 'List member boards' },
        { path: '/cards/{id}', method: 'get', operationId: 'getCard', summary: 'Get card details', parameters: [{ name: 'id', in: 'path', schema: { type: 'string' } }] },
      ],
    }),
  },
  {
    id: 'coda',
    name: 'Coda API',
    description: 'All-in-one collaborative documents, embedded tables, pages, and interactive controls.',
    category: 'Productivity & Support',
    authType: 'Bearer (CODA_API_TOKEN)',
    authEnvVar: 'CODA_API_TOKEN',
    defaultBaseUrl: 'https://coda.io/apis/v1',
    tags: ['docs', 'spreadsheets', 'automation', 'productivity'],
    bundledSpec: buildOpenAPISpec({
      title: 'Coda API',
      baseUrl: 'https://coda.io/apis/v1',
      description: 'Coda Document & Table API',
      securityScheme: { name: 'bearerAuth', type: 'http', scheme: 'bearer' },
      endpoints: [
        { path: '/whoami', method: 'get', operationId: 'whoAmI', summary: 'Get user info' },
        { path: '/docs', method: 'get', operationId: 'listDocs', summary: 'List docs' },
      ],
    }),
  },
  {
    id: 'zoom',
    name: 'Zoom Video Communications API',
    description: 'Schedule meetings, manage cloud recordings, handle webinars, and query user attendance.',
    category: 'Productivity & Support',
    authType: 'Bearer (ZOOM_OAUTH_TOKEN)',
    authEnvVar: 'ZOOM_OAUTH_TOKEN',
    defaultBaseUrl: 'https://api.zoom.us/v2',
    tags: ['video', 'meetings', 'webinars', 'recordings'],
    bundledSpec: buildOpenAPISpec({
      title: 'Zoom Video Communications API',
      baseUrl: 'https://api.zoom.us/v2',
      description: 'Zoom Meetings & Video API',
      securityScheme: { name: 'bearerAuth', type: 'http', scheme: 'bearer' },
      endpoints: [
        { path: '/users/me', method: 'get', operationId: 'getMe', summary: 'Get user profile' },
        { path: '/users/{userId}/meetings', method: 'get', operationId: 'listMeetings', summary: 'List meetings', parameters: [{ name: 'userId', in: 'path', schema: { type: 'string' } }] },
        { path: '/users/{userId}/meetings', method: 'post', operationId: 'createMeeting', summary: 'Create meeting', parameters: [{ name: 'userId', in: 'path', schema: { type: 'string' } }], requestBody: { properties: { topic: { type: 'string' }, start_time: { type: 'string' } } } },
      ],
    }),
  },
  {
    id: 'zendesk',
    name: 'Zendesk Support API',
    description: 'Customer support tickets, macros, satisfaction ratings, and knowledge base articles.',
    category: 'Productivity & Support',
    authType: 'Basic (ZENDESK_EMAIL/token:ZENDESK_API_TOKEN)',
    authEnvVar: 'ZENDESK_API_TOKEN',
    defaultBaseUrl: 'https://{subdomain}.zendesk.com/api/v2',
    tags: ['support', 'helpdesk', 'tickets', 'customer-service'],
    fieldMasks: [
      { path: '/tickets.json', fields: ['tickets.id', 'tickets.subject', 'tickets.status', 'tickets.priority', 'tickets.created_at'] },
    ],
    bundledSpec: buildOpenAPISpec({
      title: 'Zendesk Support API',
      baseUrl: 'https://example.zendesk.com/api/v2',
      description: 'Zendesk Customer Support API',
      securityScheme: { name: 'basicAuth', type: 'http', scheme: 'basic' },
      endpoints: [
        { path: '/users/me.json', method: 'get', operationId: 'getMe', summary: 'Get current user' },
        { path: '/tickets.json', method: 'get', operationId: 'listTickets', summary: 'List support tickets' },
        { path: '/tickets.json', method: 'post', operationId: 'createTicket', summary: 'Create support ticket', requestBody: { properties: { ticket: { type: 'object' } } } },
      ],
    }),
  },
  {
    id: 'intercom',
    name: 'Intercom API',
    description: 'Live customer chat conversations, contact segments, outbound campaigns, and help center.',
    category: 'Productivity & Support',
    authType: 'Bearer (INTERCOM_ACCESS_TOKEN)',
    authEnvVar: 'INTERCOM_ACCESS_TOKEN',
    defaultBaseUrl: 'https://api.intercom.io',
    tags: ['chat', 'customer-support', 'conversations', 'crm'],
    bundledSpec: buildOpenAPISpec({
      title: 'Intercom API',
      baseUrl: 'https://api.intercom.io',
      description: 'Intercom Customer Communications API',
      securityScheme: { name: 'bearerAuth', type: 'http', scheme: 'bearer' },
      endpoints: [
        { path: '/me', method: 'get', operationId: 'getMe', summary: 'Get admin profile' },
        { path: '/conversations', method: 'get', operationId: 'listConversations', summary: 'List customer conversations' },
        { path: '/contacts', method: 'get', operationId: 'listContacts', summary: 'List contacts' },
      ],
    }),
  },
  {
    id: 'front',
    name: 'Front API',
    description: 'Shared inbox collaboration, email routing rules, and multi-channel customer communications.',
    category: 'Productivity & Support',
    authType: 'Bearer (FRONT_API_TOKEN)',
    authEnvVar: 'FRONT_API_TOKEN',
    defaultBaseUrl: 'https://api2.frontapp.com',
    tags: ['shared-inbox', 'email', 'support', 'team-communication'],
    bundledSpec: buildOpenAPISpec({
      title: 'Front API',
      baseUrl: 'https://api2.frontapp.com',
      description: 'Front Shared Inbox API',
      securityScheme: { name: 'bearerAuth', type: 'http', scheme: 'bearer' },
      endpoints: [
        { path: '/me', method: 'get', operationId: 'getMe', summary: 'Get current user' },
        { path: '/inboxes', method: 'get', operationId: 'listInboxes', summary: 'List team inboxes' },
        { path: '/conversations', method: 'get', operationId: 'listConversations', summary: 'List conversations' },
      ],
    }),
  },
  {
    id: 'helpscout',
    name: 'Help Scout Mailbox API',
    description: 'Shared team mailboxes, customer support conversations, docs articles, and beacon metrics.',
    category: 'Productivity & Support',
    authType: 'Bearer (HELPSCOUT_ACCESS_TOKEN)',
    authEnvVar: 'HELPSCOUT_ACCESS_TOKEN',
    defaultBaseUrl: 'https://api.helpscout.net/v2',
    tags: ['helpdesk', 'support', 'mailboxes', 'conversations'],
    bundledSpec: buildOpenAPISpec({
      title: 'Help Scout Mailbox API',
      baseUrl: 'https://api.helpscout.net/v2',
      description: 'Help Scout Mailbox API',
      securityScheme: { name: 'bearerAuth', type: 'http', scheme: 'bearer' },
      endpoints: [
        { path: '/users/me', method: 'get', operationId: 'getMe', summary: 'Get current user' },
        { path: '/mailboxes', method: 'get', operationId: 'listMailboxes', summary: 'List mailboxes' },
        { path: '/conversations', method: 'get', operationId: 'listConversations', summary: 'List customer conversations' },
      ],
    }),
  },
];
