import { Preset } from '../types.js';

export const PRODUCTIVITY_SUPPORT_PRESETS: Preset[] = [
  {
    id: 'notion',
    name: 'Notion API',
    description: 'Query and mutate Notion workspaces, databases, pages, nested blocks, and user comments.',
    category: 'Productivity & Support',
    authType: 'Bearer (NOTION_API_KEY)',
    authEnvVar: 'NOTION_API_KEY',
    defaultBaseUrl: 'https://api.notion.com/v1',
    tags: ['docs', 'wiki', 'databases', 'pages', 'notes'],
  },
  {
    id: 'slack',
    name: 'Slack Web API',
    description: 'Post messages to channels, manage user groups, trigger modals, and upload file attachments.',
    category: 'Productivity & Support',
    authType: 'Bearer (SLACK_BOT_TOKEN)',
    authEnvVar: 'SLACK_BOT_TOKEN',
    defaultBaseUrl: 'https://slack.com/api',
    specUrl: 'https://raw.githubusercontent.com/slackapi/slack-api-specs/master/web-api/slack_web_openapi_v2.json',
    tags: ['chat', 'messaging', 'bots', 'channels', 'collaboration'],
    macros: [
      {
        name: 'postToChannel',
        description: 'Sends a formatted message to a specific Slack channel',
        parameters: {
          type: 'object',
          properties: {
            channel: { type: 'string', description: 'Channel ID or name' },
            text: { type: 'string', description: 'Message body' },
          },
          required: ['channel', 'text'],
        },
        steps: [
          { id: 'postMsg', action: 'POST /chat.postMessage', body: { channel: '{{channel}}', text: '{{text}}' } },
        ],
      },
    ],
  },
  {
    id: 'discord',
    name: 'Discord API',
    description: 'Discord bot automation, server administration, voice channels, and rich embedded messages.',
    category: 'Productivity & Support',
    authType: 'Header (Authorization: Bot ...)',
    authEnvVar: 'DISCORD_BOT_TOKEN',
    defaultBaseUrl: 'https://discord.com/api/v10',
    tags: ['chat', 'gaming', 'community', 'bots', 'guilds'],
  },
  {
    id: 'airtable',
    name: 'Airtable REST API',
    description: 'Relational database sheets, record filtering, formula fields, and view automations.',
    category: 'Productivity & Support',
    authType: 'Bearer (AIRTABLE_PERSONAL_ACCESS_TOKEN)',
    authEnvVar: 'AIRTABLE_API_KEY',
    defaultBaseUrl: 'https://api.airtable.com/v0',
    tags: ['spreadsheet', 'database', 'nocode', 'tables', 'records'],
  },
  {
    id: 'asana',
    name: 'Asana API',
    description: 'Team tasks, milestones, portfolios, subtasks, custom fields, and project timelines.',
    category: 'Productivity & Support',
    authType: 'Bearer (ASANA_ACCESS_TOKEN)',
    authEnvVar: 'ASANA_ACCESS_TOKEN',
    defaultBaseUrl: 'https://app.asana.com/api/1.0',
    tags: ['tasks', 'projects', 'collaboration', 'teams'],
  },
  {
    id: 'monday',
    name: 'Monday.com GraphQL/REST API',
    description: 'Work OS boards, column updates, item tracking, and workflow automation.',
    category: 'Productivity & Support',
    authType: 'Bearer (MONDAY_API_TOKEN)',
    authEnvVar: 'MONDAY_API_TOKEN',
    defaultBaseUrl: 'https://api.monday.com/v2',
    tags: ['work-management', 'boards', 'items', 'teams'],
  },
  {
    id: 'clickup',
    name: 'ClickUp API',
    description: 'Spaces, folders, lists, task statuses, time tracking, and custom field management.',
    category: 'Productivity & Support',
    authType: 'Bearer (CLICKUP_API_TOKEN)',
    authEnvVar: 'CLICKUP_API_TOKEN',
    defaultBaseUrl: 'https://api.clickup.com/api/v2',
    tags: ['tasks', 'productivity', 'project-management', 'time-tracking'],
  },
  {
    id: 'trello',
    name: 'Trello REST API',
    description: 'Kanban boards, lists, cards, checklist items, and power-up webhooks.',
    category: 'Productivity & Support',
    authType: 'Query (key=...&token=...)',
    authEnvVar: 'TRELLO_TOKEN',
    defaultBaseUrl: 'https://api.trello.com/1',
    tags: ['kanban', 'cards', 'boards', 'collaboration'],
  },
  {
    id: 'coda',
    name: 'Coda API',
    description: 'All-in-one collaborative documents, embedded tables, pages, and interactive controls.',
    category: 'Productivity & Support',
    authType: 'Bearer (CODA_API_TOKEN)',
    authEnvVar: 'CODA_API_TOKEN',
    defaultBaseUrl: 'https://coda.io/apis/v1',
    tags: ['docs', 'spreadsheets', 'automation', 'productivity'],
  },
  {
    id: 'zoom',
    name: 'Zoom Video Communications API',
    description: 'Schedule meetings, manage cloud recordings, handle webinars, and query user attendance.',
    category: 'Productivity & Support',
    authType: 'Bearer (ZOOM_OAUTH_TOKEN)',
    authEnvVar: 'ZOOM_OAUTH_TOKEN',
    defaultBaseUrl: 'https://api.zoom.us/v2',
    tags: ['video', 'meetings', 'webinars', 'recordings'],
  },
  {
    id: 'zendesk',
    name: 'Zendesk Support API',
    description: 'Customer support tickets, macros, satisfaction ratings, and knowledge base articles.',
    category: 'Productivity & Support',
    authType: 'Basic (ZENDESK_EMAIL/token:ZENDESK_API_TOKEN)',
    authEnvVar: 'ZENDESK_API_TOKEN',
    defaultBaseUrl: 'https://{subdomain}.zendesk.com/api/v2',
    tags: ['support', 'helpdesk', 'tickets', 'customer-service'],
  },
  {
    id: 'intercom',
    name: 'Intercom API',
    description: 'Live customer chat conversations, contact segments, outbound campaigns, and help center.',
    category: 'Productivity & Support',
    authType: 'Bearer (INTERCOM_ACCESS_TOKEN)',
    authEnvVar: 'INTERCOM_ACCESS_TOKEN',
    defaultBaseUrl: 'https://api.intercom.io',
    tags: ['chat', 'customer-support', 'conversations', 'crm'],
  },
  {
    id: 'front',
    name: 'Front API',
    description: 'Shared inbox collaboration, email routing rules, and multi-channel customer communications.',
    category: 'Productivity & Support',
    authType: 'Bearer (FRONT_API_TOKEN)',
    authEnvVar: 'FRONT_API_TOKEN',
    defaultBaseUrl: 'https://api2.frontapp.com',
    tags: ['shared-inbox', 'email', 'support', 'team-communication'],
  },
  {
    id: 'helpscout',
    name: 'Help Scout Mailbox API',
    description: 'Shared team mailboxes, customer support conversations, docs articles, and beacon metrics.',
    category: 'Productivity & Support',
    authType: 'Bearer (HELPSCOUT_ACCESS_TOKEN)',
    authEnvVar: 'HELPSCOUT_ACCESS_TOKEN',
    defaultBaseUrl: 'https://api.helpscout.net/v2',
    tags: ['helpdesk', 'support', 'mailboxes', 'conversations'],
  },
];
